window.TRIP = {
  title: "日本七日",
  subtitle: "10 月 · 两人小白，偏摄影",
  route: "北京 → 10/05 19:20 关西机场进大阪 → 奈良 → 京都整天 → DAY 04 07:45 关西飞成田 → 10/12 15:05 成田出",
  flights: {
    inbound: {
      date: "10/05 周一",
      time: "19:20",
      airport: "关西国际机场（KIX）",
      note: "出关取行李后坐南海电车到难波，换御堂筋线到本町放行李，大约 22:00–22:30 到酒店。人还不困就下楼去心斋桥拍固力果、逛还开着的药妆；困了就睡。固力果夜景以明天 citywalk 结尾那一次为准，不要两晚占同一个机位。"
    },
    outbound: {
      date: "10/12 周一",
      time: "15:05",
      airport: "成田国际机场（NRT）",
      note: "国际航班提前 4 小时到场。南千住坐常磐线到日暮里换 Skyliner，或上野换成田特快，约 09:40 出发。"
    },
    domestic: {
      date: "10/09 周五",
      time: "07:45–09:15",
      from: "关西国际机场（KIX）",
      to: "成田国际机场（NRT）",
      note: "已订。国内航班，仍要带护照。本町约 04:50 退房，打车去南海难波赶 05:15 空港急行。成田坐 Skyliner 到日暮里，再去南千住寄行李。"
    }
  },
  budget: {
    jpyToCny: 0.048,
    roundTripCny: 3000,
    visaCny: 800,
    stays: [
      { city: "大阪本町彩鸿", nights: 4, roomJpy: 500 / 0.048 },
      { city: "东京 MW Hotel", nights: 3, roomJpy: 600 / 0.048 }
    ]
  },
  hotels: {
    osaka: {
      name: "大阪本町彩鸿酒店",
      en: "Travelodge Honmachi Osaka",
      address: "大阪府大阪市中央区安土町3-2-6",
      addressEn: "3-2-6 Azuchimachi, Chuo-ku, Osaka 541-0052",
      phone: "06-4963-2196",
      station: "本町 / 堺筋本町",
      lat: 34.68435,
      lng: 135.50275
    },
    tokyo: {
      name: "MW Hotel",
      en: "MW Hotel",
      address: "东京都荒川区南千住5-31-11",
      addressEn: "5-31-11 Minamisenju, Arakawa-ku, Tokyo 116-0003",
      station: "南千住（JR / 日比谷线 / 筑波快线）",
      lat: 35.7336,
      lng: 139.7938
    }
  },
  spots: [
    {
      id: "osaka-castle",
      region: "osaka",
      area: "大阪城",
      group: "DAY 01 · 大阪 · 大阪城",
      name: "大阪城公园",
      en: "Osaka Castle Park",
      enter: "本町坐中央线到森ノ宮最方便。也可谷町线「谷町四丁目」。公园免费。今天不要上天守。",
      duration: "1 小时",
      note: "今天后面点多，不要上天守排队。拍石垣、护城河和天守同框即可。10 月公园开始有秋色。",
      guide: "大阪城是丰臣秀吉统一战国时的大本营，今天的天守是昭和重建，但巨大石垣还是当年的。它告诉你关西不是只有吃：这里曾是日本政治的中心之一。公园空旷，适合从东京水泥丛林对照着看另一种尺度。",
      xhs: ["大阪城公园", "大阪城天守阁外观"],
      photo: "大阪城",
      img: "img/spots/osaka-castle-1.jpg",
      imgs: ["img/spots/osaka-castle-1.jpg", "img/spots/osaka-castle-2.jpg", "img/spots/osaka-castle-3.jpg"],
      map: "Osaka Castle",
      lat: 34.6873,
      lng: 135.5262,
      day: 1
    },
    {
      id: "shitennoji",
      region: "osaka",
      area: "天王寺",
      group: "DAY 01 · 大阪 · 四天王寺",
      name: "四天王寺",
      en: "Shitennō-ji",
      enter: "谷町线「四天王寺前夕陽ヶ丘」。中心伽蓝要门票，约 300 日元。外围参道免费。",
      duration: "40–50 分钟",
      note: "大阪最老的官方寺院之一。拍五重塔和石鸟居即可，不必慢慢拜完。后面还要去通天阁。",
      guide: "四天王寺据说是圣德太子建的，是大阪城里还活着的古寺。天守是重建的城，这里是重建的寺，但轴线还在：南大门、五重塔、金堂排成一条线。从大阪城往南走到这里，等于把「城」和「寺」同一天看完，再进新世界的通天阁。",
      xhs: ["四天王寺", "四天王寺五重塔"],
      photo: "四天王寺",
      img: "img/spots/shitennoji-1.jpg",
      imgs: ["img/spots/shitennoji-1.jpg", "img/spots/shitennoji-2.jpg", "img/spots/shitennoji-3.jpg"],
      map: "Shitennoji Osaka",
      lat: 34.6544,
      lng: 135.5164,
      day: 1
    },
    {
      id: "tsutenkaku",
      region: "osaka",
      area: "新世界",
      group: "DAY 01 · 大阪 · 通天阁",
      name: "通天阁 · 新世界",
      en: "Tsūtenkaku & Shinsekai",
      enter: "四天王寺步行约 15 分钟，或堺筋线「惠美须町」。塔下免费拍外观。上展望台另买票，约 900 日元，时间紧就不上。",
      duration: "40 分钟（含外观）",
      note: "招牌是塔和比尔肯脚底。新世界串炸当午饭。点多就拍外观，不要为了登顶把后面狮子头挤掉。",
      guide: "通天阁是昭和大阪的塔，比东京塔更市井。脚下新世界是旧娱乐区：霓虹、串炸、还愿的比尔肯。它和大阪城不是一种「大阪」：一边是战国石垣，一边是庶民夜里出来玩的塔。第一次来，把塔放进街道里拍，比单纯上楼更像大阪。",
      xhs: ["通天阁", "新世界串炸"],
      photo: "通天阁",
      img: "img/spots/tsutenkaku-1.jpg",
      imgs: ["img/spots/tsutenkaku-1.jpg", "img/spots/tsutenkaku-2.jpg", "img/spots/tsutenkaku-3.jpg"],
      map: "Tsutenkaku Osaka",
      lat: 34.6526,
      lng: 135.5064,
      day: 1
    },
    {
      id: "namba-yasaka",
      region: "osaka",
      area: "难波",
      group: "DAY 01 · 大阪 · 难波八阪",
      name: "难波八阪神社",
      en: "Namba Yasaka Shrine",
      enter: "难波站步行约 10 分钟。境内免费。狮子殿是拍照点。",
      duration: "20–30 分钟",
      note: "12 米高狮子头是网红机位。站正前方会排队，侧拍、等人空隙。不要爬上去、不要挡参拜。",
      guide: "难波八阪神社藏在难波巷子里，一眼看到的是 1974 年造的狮子殿：张开的大口据说吞厄运、招胜运。它不是古建筑，是大阪人给自己做的象征。拍完往北走就是黑门和心斋桥，城市从神社一下回到市场。",
      xhs: ["难波八阪神社", "难波狮子头"],
      photo: "难波八阪神社",
      img: "img/spots/namba-yasaka-1.jpg",
      imgs: ["img/spots/namba-yasaka-1.jpg", "img/spots/namba-yasaka-2.jpg", "img/spots/namba-yasaka-3.jpg"],
      map: "Namba Yasaka Shrine",
      lat: 34.6614,
      lng: 135.4966,
      day: 1
    },
    {
      id: "kuromon",
      region: "osaka",
      area: "难波",
      group: "DAY 01 · 大阪 · 黑门市场",
      name: "黑门市场",
      en: "Kuromon Market",
      enter: "近铁日本桥或难波步行约 5 分钟。市场免费逛。傍晚部分摊会收。",
      duration: "45–60 分钟",
      note: "水果、海鲜、和牛试吃。这顿当加餐，不要吃成正餐，晚上还要在道顿堀吃饭。先问能不能拍。",
      guide: "黑门市场是大阪的厨房，摊位挤在一条屋顶街里。它比道顿堀真实：本地人买菜、游客试和牛，蒸汽和叫声叠在一起。citywalk 把城、寺、塔、狮子走完，最后用市场接回难波的吃，再去心斋桥买药妆。",
      xhs: ["黑门市场", "黑门市场和牛"],
      photo: "黑门市场",
      img: "img/spots/kuromon-1.jpg",
      imgs: ["img/spots/kuromon-1.jpg", "img/spots/kuromon-2.jpg", "img/spots/kuromon-3.jpg"],
      map: "Kuromon Market Osaka",
      lat: 34.6654,
      lng: 135.5063,
      day: 1
    },
    {
      id: "dotonbori",
      region: "osaka",
      area: "难波",
      group: "DAY 01 · 大阪 · 道顿堀",
      name: "道顿堀 · 心斋桥",
      en: "Dotonbori & Shinsaibashi",
      enter: "地铁御堂筋线难波站或心斋桥站。街道免费。",
      duration: "1–1.5 小时（夜景）",
      note: "固力果留晚上灯亮再拍。白天只走心斋桥药妆，不要在桥上耗掉。抵达当晚若已拍过，今晚侧拍运河即可，不要两晚占同一个机位。不要站在桥中间挡路。",
      guide: "道顿堀是大阪的脸。运河、巨型招牌、章鱼烧蒸汽，构成关西最吵也最好认的夜景。心斋桥筋是旁边那条商店街。第一次来日本从大阪进，这里比东京涩谷更直白：吃、逛、拍灯，都挤在同一条水边上。",
      xhs: ["道顿堀固力果", "心斋桥夜景"],
      photo: "道顿堀",
      img: "img/spots/dotonbori-1.jpg",
      imgs: ["img/spots/dotonbori-1.jpg", "img/spots/dotonbori-2.jpg", "img/spots/dotonbori-3.jpg"],
      map: "Dotonbori Osaka",
      lat: 34.6687,
      lng: 135.5013,
      day: 1
    },
    {
      id: "fushimi",
      region: "kyoto",
      area: "伏见",
      group: "DAY 03 · 京都 · 伏见稻荷",
      name: "伏见稻荷大社",
      en: "Fushimi Inari Taisha",
      enter: "JR 奈良线稻荷站出站即到。境内免费。千本鸟居不用预约。",
      duration: "1.5–2 小时",
      note: "今晚回大阪酒店，不必赶飞机。主拍千本鸟居，可以多走一段再下来，仍不必硬登顶。不要挡住通道拍照。早上比下午空。",
      guide: "伏见稻荷供奉稻荷神，管生意和食物，是全日本分社最多的神社。橙色千本鸟居一座座叠上去，是京都对外最强的视觉符号。它不是「打卡走廊」，而是还在被当地人祈愿的山。第一次来，走进去一段、再走下来，比硬爬到山顶更合适。",
      xhs: ["伏见稻荷千本鸟居", "伏见稻荷拍照"],
      photo: "伏见稻荷",
      img: "img/spots/fushimi-1.jpg",
      imgs: ["img/spots/fushimi-1.jpg", "img/spots/fushimi-2.jpg", "img/spots/fushimi-3.jpg"],
      map: "Fushimi Inari Taisha",
      lat: 34.9671,
      lng: 135.7727,
      day: 3
    },
    {
      id: "kiyomizu",
      region: "kyoto",
      area: "东山",
      group: "DAY 03 · 京都 · 清水寺",
      name: "清水寺 · 二年坂",
      en: "Kiyomizu-dera & Ninenzaka",
      enter: "京都市巴士或地铁再换乘。清水寺本堂要门票。二年坂、产宁坂街道免费。",
      duration: "2 小时",
      note: "和伏见稻荷同一天，不用赶飞机。清水舞台看京都盆地。坡道禁止边走边吃挡路。16:30 前离开，晚饭可在祇园附近吃再回大阪。",
      guide: "清水寺悬在东山崖上，本堂不钉一根钉子的说法流传很广，舞台眺望的是整座京都盆地。下来的二年坂、产宁坂是还活着的门前町。伏见稻荷是山与鸟居，清水寺是木构和城市俯视——一天里把京都的两种「古」都走一遍。",
      xhs: ["清水寺舞台", "二年坂产宁坂"],
      photo: "清水寺",
      img: "img/spots/kiyomizu-1.jpg",
      imgs: ["img/spots/kiyomizu-1.jpg", "img/spots/kiyomizu-2.jpg", "img/spots/kiyomizu-3.jpg"],
      map: "Kiyomizu-dera Kyoto",
      lat: 34.9948,
      lng: 135.7850,
      day: 3
    },
    {
      id: "nara",
      region: "nara",
      area: "奈良公园",
      group: "DAY 02 · 奈良 · 奈良公园",
      name: "奈良公园 · 东大寺",
      en: "Nara Park & Tōdai-ji",
      enter: "近铁奈良站出站往东步行约 15 分钟。公园免费。东大寺大佛殿要门票，约 800 日元。鹿仙贝现场买。",
      duration: "2.5–3 小时",
      note: "上午只来这一次：喂鹿、看大佛。鹿会抢纸袋，贵重物品收好。仙贝买完再喂。下午改去奈良町，不要再折回公园。",
      guide: "奈良是日本第一个长期都城，东大寺大佛是奈良时代国家工程的遗物。鹿在神社里被当成神使，公园里到处走。它比京都更疏、更慢。这次不去乐园，DAY 02 用这一天补关西古都：大阪是吃和城，奈良是寺和鹿，隔天京都才是鸟居和坡道。",
      xhs: ["奈良公园小鹿", "东大寺大佛"],
      photo: "奈良",
      img: "img/spots/nara-1.jpg",
      imgs: ["img/spots/nara-1.jpg", "img/spots/nara-2.jpg", "img/spots/nara-3.jpg"],
      map: "Todai-ji Nara",
      lat: 34.6889,
      lng: 135.8398,
      day: 2
    },
    {
      id: "naramachi",
      region: "nara",
      area: "奈良町",
      group: "DAY 02 · 奈良 · 奈良町",
      name: "奈良町",
      en: "Naramachi",
      enter: "东大寺往西南步行约 15 分钟，或近铁奈良站往南走。巷子免费逛。",
      duration: "1.5–2 小时",
      note: "格子门町家、杂货店、咖啡。这是奈良的老街区，不是公园。不必再进东大寺，也不要再喂鹿。",
      guide: "奈良町是奈良迁都之后留下来的商人街区，町家格子门还在。上午在公园里看国家工程的大佛和鹿，下午走进普通人住过的巷子，奈良才完整。它比东大寺安静，适合午饭后慢慢走，再坐近铁回大阪。",
      xhs: ["奈良町", "奈良町町家"],
      photo: "奈良",
      img: "img/spots/nara-3.jpg",
      imgs: ["img/spots/nara-3.jpg", "img/spots/nara-2.jpg", "img/spots/nara-1.jpg"],
      map: "Naramachi Nara",
      lat: 34.6775,
      lng: 135.8300,
      day: 2
    },
    {
      id: "maiko",
      region: "kobe",
      area: "舞子",
      group: "DAY 02 备选 · 神户 · 舞子",
      name: "明石海峡大桥 · 舞子",
      en: "Akashi Kaikyō Bridge / Maiko",
      enter: "JR 神户线「舞子」出站往南步行约 5 分钟。舞子海上步道现场买票，平日约 250 日元，周末约 300。10 月 9:00–18:00，入场到 17:30。",
      duration: "1.5–2 小时",
      note: "大桥不用走完，只开放一段观景路。玻璃地板下面是海，恐高可走旁边。外拍桥塔和淡路岛，不必硬撑到尽头。",
      guide: "明石海峡大桥是世界上最长的悬索桥之一，连起神户和淡路岛。舞子这一侧把桥、海、列车放进同一张画面。它不是寺庙，是关西把海峡当成门的那种工程风景——和奈良的鹿、京都的鸟居是另一种日本。",
      xhs: ["舞子海上步道", "明石海峡大桥玻璃"],
      photo: "明石海峡大桥",
      img: "img/spots/maiko-1.jpg",
      imgs: ["img/spots/maiko-1.jpg", "img/spots/maiko-2.jpg", "img/spots/maiko-3.jpg"],
      map: "Maiko Marine Promenade",
      lat: 34.6372,
      lng: 135.0217,
      day: 2,
      alt: "kobe",
      altLabel: "神户"
    },
    {
      id: "suma",
      region: "kobe",
      area: "须磨",
      group: "DAY 02 备选 · 神户 · 须磨",
      name: "须磨海岸",
      en: "Suma Beach",
      enter: "JR「须磨」出站往南走几分钟到海边。免费。",
      duration: "1–1.5 小时",
      note: "出站往海边的路口常被拿来拍「镰仓同款」日系机位。沙滩干净，人比景点少，当地人钓鱼遛狗。找台阶坐下即可，不要下水。",
      guide: "须磨是神户西边的生活海岸，不是主题乐园。电车、小房子、海在一条轴线上，所以好看。上午刚从大桥下来，这里用来换节奏：把工程尺度收回成海边发呆。",
      xhs: ["须磨海岸", "须磨海岸镰仓机位"],
      photo: "须磨海岸",
      img: "img/spots/suma-1.jpg",
      imgs: ["img/spots/suma-1.jpg", "img/spots/suma-2.jpg", "img/spots/suma-3.jpg"],
      map: "Suma Beach Kobe",
      lat: 34.6395,
      lng: 135.1175,
      day: 2,
      alt: "kobe",
      altLabel: "神户"
    },
    {
      id: "ikuta",
      region: "kobe",
      area: "三宫",
      group: "DAY 02 备选 · 神户 · 生田神社",
      name: "生田神社",
      en: "Ikuta Jinja",
      enter: "JR / 阪急「三宫」步行约 8 分钟。神社免费。御守、御朱印现场买。",
      duration: "45–60 分钟",
      note: "市中心却很静。红色连承鸟居像缩小的伏见稻荷，适合空镜。御守和御朱印设计感强；绘马是白色小熊，值得买一个留念。",
      guide: "生田神社是神户最老的神社之一，祭神和开垦、航行有关。三宫再吵，鸟居后面仍是树林。关西这一天如果改走神户，这里就是「也要进一次神社」的那一站，不用再跑回京都。",
      xhs: ["生田神社", "生田神社御守", "生田神社小熊绘马"],
      photo: "生田神社",
      img: "img/spots/ikuta-1.jpg",
      imgs: ["img/spots/ikuta-1.jpg", "img/spots/ikuta-2.jpg", "img/spots/ikuta-3.jpg"],
      map: "Ikuta Shrine Kobe",
      lat: 34.6953,
      lng: 135.1887,
      day: 2,
      alt: "kobe",
      altLabel: "神户"
    },
    {
      id: "sannomiya",
      region: "kobe",
      area: "三宫",
      group: "DAY 02 备选 · 神户 · 三宫",
      name: "三宫购物",
      en: "Sannomiya",
      enter: "生田神社走回三宫站周边。唐吉诃德三宫店比心斋桥人少。",
      duration: "1.5–2 小时",
      note: "补药妆、零食比心斋桥轻松。热门款这里常有。不要买到拖不动，大件仍留东京最后一天。",
      guide: "三宫是神户的生活中心，不是观光城。电车、百货、唐吉诃德叠在一起。白天在舞子看海，晚上回到有人声的街区吃饭，神户这一天才完整。",
      xhs: ["三宫唐吉诃德", "三宫药妆"],
      photo: "三宫",
      img: "img/spots/sannomiya-1.jpg",
      imgs: ["img/spots/sannomiya-1.jpg", "img/spots/sannomiya-2.jpg", "img/spots/sannomiya-3.jpg"],
      map: "Sannomiya Kobe",
      lat: 34.6932,
      lng: 135.1955,
      day: 2,
      alt: "kobe",
      altLabel: "神户"
    },
    {
      id: "kaminarimon",
      region: "tokyo",
      area: "浅草",
      group: "DAY 04 · 东京 · 浅草",
      name: "雷门",
      en: "Kaminarimon",
      enter: "南千住坐筑波快线一站到浅草，或日比谷线到上野再换银座线。免费，不用预约。",
      duration: "15–20 分钟",
      note: "大红灯笼是浅草第一张。人多时侧拍、等人流空隙。灯笼背面也有字，可以绕过去拍。",
      guide: "雷门是浅草寺的正门，也是很多人到东京后拍下的第一张「我到了」。门上那盏巨灯笼写着「雷门」，两侧是风神和雷神，保佑过路人平安。穿过这道门，才算走进江户留下来的庶民街区浅草——它不只是背景板，是整条参拜轴的起点。",
      xhs: ["浅草雷门拍照", "雷门灯笼机位"],
      photo: "雷门",
      img: "img/spots/kaminarimon-1.jpg",
      imgs: ["img/spots/kaminarimon-1.jpg", "img/spots/kaminarimon-2.jpg", "img/spots/kaminarimon-3.jpg"],
      map: "Kaminarimon Asakusa",
      lat: 35.7111,
      lng: 139.7964,
      day: 4
    },
    {
      id: "sensoji",
      region: "tokyo",
      area: "浅草",
      group: "DAY 04 · 东京 · 浅草",
      name: "浅草寺",
      en: "Sensō-ji",
      enter: "雷门穿过仲见世即到。寺院免费。正殿大约 6:00–17:00。",
      duration: "45–60 分钟",
      note: "宝藏门、五重塔、本堂都好看。进门洗手。抽签：大吉可带走，不好的系在架子上。上午侧光更干净。",
      guide: "浅草寺是东京最古老的寺院，供奉观音。传说渔民在隅田川捞到观音像，由此建寺，所以直到今天仍是普通人求平安、求学业的地方。香炉的烟、五重塔、本堂，是最典型的「下町」寺庙样子。第一次来日本，不妨在这里跟着旁边的人学一次参拜。",
      xhs: ["浅草寺拍照", "浅草寺五重塔", "浅草寺抽签"],
      photo: "浅草寺",
      img: "img/spots/sensoji-1.jpg",
      imgs: ["img/spots/sensoji-1.jpg", "img/spots/sensoji-2.jpg", "img/spots/sensoji-3.jpg"],
      map: "Senso-ji Asakusa Tokyo",
      lat: 35.7148,
      lng: 139.7967,
      day: 4
    },
    {
      id: "nakamise",
      region: "tokyo",
      area: "浅草",
      group: "DAY 04 · 东京 · 浅草",
      name: "仲见世商店街",
      en: "Nakamise-dōri",
      enter: "雷门到宝藏门之间。公共街道，免费。",
      duration: "30 分钟",
      note: "人形烧、扇子、和风小物。站路边吃，不要边走边吃挡路。",
      guide: "仲见世是雷门到浅草寺之间那条古老商店街，江户时代就是给进香人准备的。人形烧、扇子、小物排在两侧，意义不在买多少，而在于你走在一条还活着的参拜道上——寺庙、小生意和游客叠在同一条轴线上，这就是浅草。",
      xhs: ["仲见世商店街", "浅草人形烧"],
      photo: "仲见世",
      img: "img/spots/nakamise-1.jpg",
      imgs: ["img/spots/nakamise-1.jpg", "img/spots/nakamise-2.jpg"],
      map: "Nakamise-dori Asakusa",
      lat: 35.7119,
      lng: 139.7964,
      day: 4
    },
    {
      id: "skytree",
      region: "tokyo",
      area: "押上",
      group: "DAY 04 · 东京 · 浅草",
      name: "东京晴空塔",
      en: "Tokyo Skytree",
      enter: "浅草步行约 20 分钟，或地铁到押上。天望甲板建议官网买指定时段。",
      duration: "1.5–2 小时",
      note: "10 月能见度通常不错，晴天可能看到富士山。第一次去天望甲板够用。DAY 04 上午到东京，订傍晚场看灯亮。",
      guide: "东京晴空塔 2012 年才亮相，是世界最高的自立式电波塔之一，也是东京向东看的新天际线。站上天望甲板，浅草、隅田川，运气好时连富士山都能放进同一张照片。它代表当代东京：用一座能被一眼认出来的塔，给这座巨大城市再做一个符号。",
      xhs: ["东京晴空塔展望台", "晴空塔看富士山"],
      photo: "东京晴空塔",
      img: "img/spots/skytree-1.jpg",
      imgs: ["img/spots/skytree-1.jpg", "img/spots/skytree-2.jpg", "img/spots/skytree-3.jpg"],
      map: "Tokyo Skytree",
      lat: 35.7101,
      lng: 139.8107,
      day: 4
    },
    {
      id: "akihabara",
      region: "tokyo",
      area: "秋叶原",
      group: "DAY 04 · 东京 · 秋叶原",
      name: "秋叶原",
      en: "Akihabara",
      enter: "JR 山手线秋叶原站，南千住坐日比谷线可直达。街道免费。电器店、动漫店晚上灯更亮。",
      duration: "1–1.5 小时",
      note: "中央通两侧广告牌很好拍。晚上霓虹更出片。店里有的不能拍，看告示。人多把包转到身前。",
      guide: "秋叶原从电器街长成御宅文化的门面。中央通两侧的灯牌、动漫店、女仆店招，是日本流行文化对外输出最密的一条街。晚上灯全亮，才是它真正的样子。第一次来不必强迫购物，顺着街道走、抬头拍广告墙，就能读懂东京的另一面。",
      xhs: ["秋叶原夜景", "秋叶原中央通拍照"],
      photo: "秋叶原",
      img: "img/spots/akihabara-1.jpg",
      imgs: ["img/spots/akihabara-1.jpg", "img/spots/akihabara-2.jpg", "img/spots/akihabara-3.jpg"],
      map: "Akihabara Chuo dori",
      lat: 35.6984,
      lng: 139.7731,
      day: 4
    },
    {
      id: "meiji",
      region: "tokyo",
      area: "原宿",
      group: "DAY 05 · 东京 · 原宿涩谷",
      name: "明治神宫",
      en: "Meiji Jingu",
      enter: "JR 原宿站明治神宫口。境内免费。黎明到日落。",
      duration: "1–1.5 小时",
      note: "进鸟居走两侧。森林和鸟居是原宿最干净的一张。参拜：鞠躬两次、拍手两次、再鞠躬。",
      guide: "明治神宫祭祀明治天皇与昭宪皇后，是东京正中心一片人造的深林。原宿再吵，一进鸟居就静下来。现代东京从明治维新长出来，神宫用森林把那段历史藏在时尚街区旁边。参拜很简单：鞠躬两次、拍手两次、再鞠躬，跟着旁边的人做即可。",
      xhs: ["明治神宫鸟居", "明治神宫参拜"],
      photo: "明治神宫",
      img: "img/spots/meiji-1.jpg",
      imgs: ["img/spots/meiji-1.jpg", "img/spots/meiji-2.jpg", "img/spots/meiji-3.jpg"],
      map: "Meiji Jingu Shrine",
      lat: 35.6764,
      lng: 139.6993,
      day: 5
    },
    {
      id: "takeshita",
      region: "tokyo",
      area: "原宿",
      group: "DAY 05 · 东京 · 原宿涩谷",
      name: "竹下通",
      en: "Takeshita Street",
      enter: "JR 原宿站竹下口对面。免费。",
      duration: "30–40 分钟",
      note: "年轻街拍、可丽饼。周末极挤，背包放身前。",
      guide: "竹下通是原宿的年轻街区，可丽饼、古着、街头时尚从这里传到全世界。它没有古迹，特色就是「此刻的东京年轻人怎么玩」。周末会挤到几乎走不动，适合快看、买个吃的，把时间留给旁边的神宫和表参道。",
      xhs: ["竹下通可丽饼", "原宿竹下通"],
      photo: "原宿",
      img: "img/spots/takeshita-1.jpg",
      imgs: ["img/spots/takeshita-1.jpg", "img/spots/takeshita-3.jpg"],
      map: "Takeshita Dori Harajuku",
      lat: 35.6705,
      lng: 139.7061,
      day: 5
    },
    {
      id: "omotesando",
      region: "tokyo",
      area: "表参道",
      group: "DAY 05 · 东京 · 原宿涩谷",
      name: "表参道",
      en: "Omotesandō",
      enter: "竹下通往南，或地铁表参道站。街道免费。",
      duration: "40 分钟",
      note: "10 月银杏开始转黄，建筑和橱窗好拍。比竹下通安静。",
      guide: "表参道原本是通往明治神宫的参拜大道，后来长成东京最讲究的林荫商业街。建筑、橱窗、银杏沿路排开。竹下通吵、表参道从容，两条街拼在一起，才是完整的原宿：一边是年轻人的现在，一边是参拜道变成的时髦。",
      xhs: ["表参道银杏", "表参道建筑"],
      photo: "表参道",
      img: "img/spots/omotesando-1.jpg",
      imgs: ["img/spots/omotesando-1.jpg", "img/spots/omotesando-2.jpg", "img/spots/omotesando-3.jpg"],
      map: "Omotesando Tokyo",
      lat: 35.6654,
      lng: 139.7123,
      day: 5
    },
    {
      id: "shibuya",
      region: "tokyo",
      area: "涩谷",
      group: "DAY 05 · 东京 · 原宿涩谷",
      name: "涩谷十字路口 · 中心街",
      en: "Shibuya Crossing & Center-gai",
      enter: "JR 涩谷站八公口。路口和中心街免费。",
      duration: "40–50 分钟",
      note: "绿灯时从人行道中间回头拍人潮。八公像很小，合影请快。晚上中心街霓虹更好看。",
      guide: "涩谷十字路口常被称为世界上最繁忙的人行横道。绿灯一亮，四面的人在路口中央交错，是东京密度和秩序同时存在的象征。旁边的忠犬八公像纪念那只等主人回家的秋田犬，也是最常用的碰头点。晚上再走进中心街，霓虹才真正铺开。",
      xhs: ["涩谷十字路口拍照", "涩谷中心街夜景", "忠犬八公像"],
      photo: "涩谷",
      img: "img/spots/shibuya-2.jpg",
      imgs: ["img/spots/shibuya-2.jpg", "img/spots/shibuya-1.jpg", "img/spots/shibuya-3.jpg"],
      map: "Shibuya Crossing Tokyo",
      lat: 35.6595,
      lng: 139.7004,
      day: 5
    },
    {
      id: "shibuya-sky",
      region: "tokyo",
      area: "涩谷",
      group: "DAY 05 · 东京 · 原宿涩谷",
      name: "SHIBUYA SKY 夜景",
      en: "SHIBUYA SKY",
      enter: "涩谷 Scramble Square 14 楼买票入场，电梯到 46 楼再上屋顶。必须提前买指定日指定时段票，周六夜很难现场买到。",
      duration: "1–1.5 小时",
      note: "10/10 周六，订晚上 19:30–20:30 入场。屋顶无玻璃，风大，带薄外套。不要用脚踩玻璃边框。拍完十字路口再上来，灯全亮更好看。",
      guide: "SHIBUYA SKY 在涩谷十字路口正上方，是目前看「脚下那团人潮和霓虹」最好的地方。晴空塔看的是远景东京，这里看的是涩谷本身：路口、109、铁路和夜灯叠在一起。第一次来、又偏摄影，这张夜景值得单独买票，不要只在地面拍路口。",
      xhs: ["SHIBUYA SKY夜景", "涩谷SKY拍照"],
      photo: "涩谷天空",
      img: "img/spots/shibuya-sky-1.jpg",
      imgs: ["img/spots/shibuya-sky-1.jpg", "img/spots/shibuya-sky-2.jpg", "img/spots/shibuya-sky-3.jpg"],
      map: "SHIBUYA SKY",
      lat: 35.6584,
      lng: 139.7022,
      day: 5
    },
    {
      id: "tokyo-tower",
      region: "tokyo",
      area: "芝公园",
      group: "DAY 05 · 东京 · 港区",
      name: "东京塔",
      en: "Tokyo Tower",
      enter: "地铁赤羽桥站或神谷町站。塔下芝公园免费拍外观。上展望台要票，建议官网。",
      duration: "1–1.5 小时",
      note: "红白塔身白天、晚上都好拍。增上寺门框里套东京塔是经典机位。10 月日落大约 17:10。今晚还要回涩谷上 SKY，塔下拍亮灯即可，不要上展望台。",
      guide: "东京塔 1958 年建成，造型模仿埃菲尔铁塔，红白涂装是为了航空警示。很长一段时间里，它就是「东京」两个字的视觉符号，比晴空塔更有昭和味道。增上寺山门把塔框进去，等于把江户寺庙和战后铁塔叠在同一张画面里。",
      xhs: ["东京塔增上寺", "东京塔夜景拍照"],
      photo: "东京塔",
      img: "img/spots/tokyo-tower-1.jpg",
      imgs: ["img/spots/tokyo-tower-1.jpg", "img/spots/tokyo-tower-2.jpg", "img/spots/tokyo-tower-3.jpg"],
      map: "Tokyo Tower",
      lat: 35.6586,
      lng: 139.7454,
      day: 5
    },
    {
      id: "disneysea",
      region: "maihama",
      area: "舞浜",
      group: "备选 · 千叶 · 这次不去",
      name: "东京迪士尼海洋",
      en: "Tokyo DisneySea",
      enter: "必须提前买指定日门票。JR 京叶线舞浜，再坐度假区线到海洋。现场不售票。",
      duration: "一整天",
      note: "这次不去主题乐园。以后若想看港湾夜景再排，不要和市内摄影日挤在同一周。",
      guide: "东京迪士尼海洋是全世界独有的海洋主题迪士尼，七大港口围着地中海港湾。这次行程偏城市和古都摄影，乐园整天先不排。",
      xhs: ["迪士尼海洋地中海港湾", "东京迪士尼海洋拍照"],
      photo: "东京迪士尼海洋",
      img: "img/spots/disneysea-1.jpg",
      imgs: ["img/spots/disneysea-1.jpg", "img/spots/disneysea-2.jpg", "img/spots/disneysea-3.jpg"],
      map: "Tokyo DisneySea",
      lat: 35.6267,
      lng: 139.8851,
      optional: true,
      day: 0,
      onMap: false
    },
    {
      id: "tsukiji",
      region: "tokyo",
      area: "筑地",
      group: "DAY 06 · 东京 · 都心",
      name: "筑地场外市场",
      en: "Tsukiji Outer Market",
      enter: "日比谷线筑地站，南千住可直达。场外免费逛。内市场已迁丰洲，不要跑错。",
      duration: "1.5 小时（含早饭）",
      note: "海鲜颜色好拍，先问能不能拍。店小，两人拼桌常见。",
      guide: "筑地曾是世界最大的鱼市场。2018 年内市场迁去丰洲，场外市场还留在原地，寿司、海鲜丼、刀具店挤在巷子里。你在这里吃的是东京人对新鲜海产的执念，也是一层还没被商场替换掉的市井气味。记住：不要跑去丰洲找「老筑地」。",
      xhs: ["筑地场外市场寿司", "筑地早饭"],
      photo: "筑地市场",
      img: "img/spots/tsukiji-1.jpg",
      imgs: ["img/spots/tsukiji-1.jpg", "img/spots/tsukiji-2.jpg", "img/spots/tsukiji-3.jpg"],
      map: "Tsukiji Outer Market",
      lat: 35.6654,
      lng: 139.7707,
      day: 6
    },
    {
      id: "ginza",
      region: "tokyo",
      area: "银座",
      group: "DAY 06 · 东京 · 都心",
      name: "银座",
      en: "Ginza",
      enter: "筑地步行约 15 分钟。周日白天常有步行者天国。",
      duration: "1 小时",
      note: "和光钟楼是地标。晚上霓虹更好看。大件留到最后一天再买。",
      guide: "银座是东京最早的西式砖街之一，明治时期就代表「最时髦的日本」。和光钟楼、三越、步行者天国，是金钱、橱窗和礼仪同时很讲究的地方。不一定要买东西，顺着中央通走一段，就能感到这座城市把消费也做成了风景。",
      xhs: ["银座和光", "银座夜景"],
      photo: "银座",
      img: "img/spots/ginza-1.jpg",
      imgs: ["img/spots/ginza-1.jpg", "img/spots/ginza-2.jpg", "img/spots/ginza-3.jpg"],
      map: "Ginza Tokyo",
      lat: 35.6712,
      lng: 139.7649,
      day: 6
    },
    {
      id: "imperial",
      region: "tokyo",
      area: "千代田",
      group: "DAY 06 · 东京 · 都心",
      name: "皇居外苑 · 二重桥",
      en: "Imperial Palace Nijubashi",
      enter: "二重桥前站或樱田门站。外苑免费。",
      duration: "45 分钟",
      note: "拍双重桥和石墙即可。广场空旷，帽子有用。",
      guide: "皇居是天皇居住的地方，一般游客只到外苑和二重桥。双重拱桥、护城河和石墙，把「日本还有一个皇家中心」变成能看见的风景。广场空旷、天空很大，和浅草、涩谷完全相反——东京也有故意留白的一面。",
      xhs: ["皇居二重桥", "皇居外苑"],
      photo: "皇居",
      img: "img/spots/imperial-1.jpg",
      imgs: ["img/spots/imperial-1.jpg", "img/spots/imperial-2.jpg", "img/spots/imperial-3.jpg"],
      map: "Nijubashi Imperial Palace",
      lat: 35.6802,
      lng: 139.7544,
      day: 6
    },
    {
      id: "tokyo-station",
      region: "tokyo",
      area: "丸之内",
      group: "DAY 06 · 东京 · 都心",
      name: "东京站丸之内",
      en: "Tokyo Station Marunouchi",
      enter: "JR 东京站丸之内口。外观和 KITTE 屋顶免费。",
      duration: "40 分钟",
      note: "红砖车站是经典机位。KITTE 屋顶能拍全景。傍晚灯亮更好看。",
      guide: "东京站丸之内红砖站房由辰野金吾设计，1914 年启用，战后按原貌修复。它是日本铁路网的心脏，也是把欧洲车站美学搬进东京的纪念碑。KITTE 屋顶能看到完整立面，傍晚灯亮时最像明信片。",
      xhs: ["东京站丸之内", "KITTE屋顶东京站"],
      photo: "东京车站",
      img: "img/spots/station-1.jpg",
      imgs: ["img/spots/station-1.jpg", "img/spots/station-2.jpg", "img/spots/station-3.jpg"],
      map: "Tokyo Station Marunouchi",
      lat: 35.6812,
      lng: 139.7671,
      day: 6
    },
    {
      id: "shinkansen",
      region: "tokyo",
      area: "东京站",
      group: "备选 · 东京 · 新干线外观",
      name: "新干线（东京站拍车头）",
      en: "Shinkansen at Tokyo Station",
      enter: "东京站新干线口。进站台通常要车票或站台票。外观可在丸之内先拍车站。",
      duration: "20–30 分钟",
      note: "这次大阪到东京坐飞机，没有坐新干线。还想拍车头，用站台票进东京站新干线口，拍完出站即可。",
      guide: "新干线 1964 年通车，是日本速度、准点和战后复兴的象征。车头那张「大嘴」照片，对很多人来说等于见过日本的火车。这次城际改成飞机，进站台看一眼就够；真要坐车看风景，留给伊豆备选那天的热海方向。",
      xhs: ["东京站新干线拍照", "N700S车头"],
      photo: "新干线",
      img: "img/spots/shinkansen-1.jpg",
      imgs: ["img/spots/shinkansen-1.jpg", "img/spots/shinkansen-2.jpg", "img/spots/shinkansen-3.jpg"],
      map: "Tokyo Station Shinkansen",
      lat: 35.6814,
      lng: 139.7660,
      optional: true,
      day: 0
    },
    {
      id: "kawaguchiko",
      region: "fuji",
      area: "河口湖",
      group: "备选 · 山梨 · 这次不去",
      name: "河口湖",
      en: "Lake Kawaguchi",
      enter: "去新宿坐高速巴士，约 1 小时 45 分到河口湖站。湖畔免费。",
      duration: "大半天",
      note: "这次主线是关西进东京出，不去河口湖。以后若从东京出发再排。",
      guide: "河口湖是富士五湖里最容易从东京到达、也最好拍倒影的一座。湖、小镇、富士山，构成关东人最熟悉的「出城看山」线路。10 月空气相对干净，山是否露脸全看云。来这里不只是打卡富士，也是离开水泥东京一天，把节奏放慢。",
      xhs: ["河口湖拍富士山", "大石公园富士山"],
      photo: "河口湖",
      img: "img/spots/kawaguchiko-1.jpg",
      imgs: ["img/spots/kawaguchiko-1.jpg", "img/spots/kawaguchiko-2.jpg", "img/spots/kawaguchiko-3.jpg"],
      map: "Lake Kawaguchi",
      lat: 35.5170,
      lng: 138.7519,
      optional: true,
      day: 0,
      onMap: false
    },
    {
      id: "fuji",
      region: "fuji",
      area: "河口湖",
      group: "备选 · 山梨 · 这次不去",
      name: "富士山观景",
      en: "Mount Fuji View",
      enter: "河口湖一带多个观景点。新仓山浅间公园要爬台阶，天气好时塔和富士同框。",
      duration: "1–2 小时",
      note: "这次行程删掉富士山相关安排。经典机位在新仓山，不要塞进大阪–东京这 6 天。",
      guide: "富士山是日本最高峰，也是浮世绘和课本里的国家象征。河口湖这边最经典的构图在新仓山浅间公园：五重塔、树木，远处是雪顶。山在文化里很神圣，天气不好时不必死等——云本身也是富士的一部分。",
      xhs: ["新仓山浅间公园", "河口湖五重塔富士山"],
      photo: "富士山",
      img: "img/spots/fuji-2.jpg",
      imgs: ["img/spots/fuji-2.jpg", "img/spots/fuji-3.jpg", "img/spots/kawaguchiko-1.jpg"],
      map: "Arakurayama Sengen Park",
      lat: 35.5013,
      lng: 138.8016,
      optional: true,
      day: 0,
      onMap: false
    },
    {
      id: "gyoen",
      region: "tokyo",
      area: "新宿",
      group: "备选 · 东京 · 新宿御苑",
      name: "新宿御苑",
      en: "Shinjuku Gyoen",
      enter: "从南千住先到新宿，东南口再步行约 10 分钟。成人 500 日元。周一休园。",
      duration: "1–1.5 小时",
      note: "10/12 返程是周一，御苑休园。想去就插到东京市内某天空档，不要单独再排一整天。",
      guide: "新宿御苑曾是江户大名宅邸，后来变成皇室花园，再向公众开放。日式、英式、法式庭园挨在一起，是新宿水泥森林里少有的大片绿地。周一休园，所以没排进返程那天。想去就插在市内某天的空档，慢慢走比赶点合适。",
      xhs: ["新宿御苑拍照", "新宿御苑周一休园"],
      photo: "新宿御苑",
      img: "img/spots/gyoen-1.jpg",
      imgs: ["img/spots/gyoen-1.jpg", "img/spots/gyoen-2.jpg", "img/spots/gyoen-3.jpg"],
      map: "Shinjuku Gyoen",
      lat: 35.6852,
      lng: 139.7100,
      day: 0,
      optional: true
    },
    {
      id: "tmg",
      region: "tokyo",
      area: "西新宿",
      group: "备选 · 东京 · 新宿",
      name: "都厅展望室",
      en: "Tokyo Metropolitan Government Building",
      enter: "从南千住先到新宿西口，再步行约 10 分钟。免费，不用预约。",
      duration: "40 分钟",
      note: "10/12 成田 15:05 起飞，当天早上去机场，来不及上都厅。从南千住去新宿大约 35 分钟，想去就插到东京市内某天空档。",
      guide: "东京都厅是东京都政府办公楼，丹下健三设计，两座塔楼像哥特教堂。顶楼展望室免费，能看西边的富士和脚下的新宿。它代表「行政东京」：不是寺庙也不是商店街，而是这座超大城市如何被管理。这次住南千住，去新宿要额外一趟，想去就插在市内某天空档。",
      xhs: ["都厅展望台夜景", "新宿都厅免费"],
      photo: "东京都厅",
      img: "img/spots/tmg-2.jpg",
      imgs: ["img/spots/tmg-2.jpg", "img/spots/tmg-3.jpg"],
      map: "Tokyo Metropolitan Government Building",
      lat: 35.6896,
      lng: 139.6917,
      day: 0,
      optional: true
    },
    {
      id: "disneyland",
      region: "maihama",
      area: "舞浜",
      group: "备选 · 千叶 · 这次不去",
      name: "东京迪士尼乐园",
      en: "Tokyo Disneyland",
      enter: "和海洋是两个园，门票不能通用。JR 京叶线舞浜。",
      duration: "一整天",
      note: "这次不去主题乐园。城堡和游行留给以后单独排一天。",
      guide: "东京迪士尼乐园是亚洲第一座迪士尼。和海洋是两个园，票不能混用。这次主线不排任何乐园。",
      xhs: ["东京迪士尼城堡", "东京迪士尼万圣节"],
      photo: "东京迪士尼乐园",
      img: "img/spots/disneyland-1.jpg",
      imgs: ["img/spots/disneyland-1.jpg", "img/spots/disneyland-2.jpg", "img/spots/disneyland-3.jpg"],
      map: "Tokyo Disneyland",
      lat: 35.6329,
      lng: 139.8804,
      day: 0,
      optional: true,
      onMap: false
    },
    {
      id: "omuroyama",
      region: "izu",
      area: "伊豆高原",
      group: "备选 · 静冈 · 伊豆",
      name: "大室山",
      en: "Mount Ōmuro",
      enter: "新干线东京→热海，再伊豆急行到伊豆高原。上山坐缆车。这次主线不去；若以后从东京出发再排，不要和市内摄影日冲突。",
      duration: "半天（含交通则一整天）",
      note: "草山像绿帽子，山顶一圈能看海。10 月天气好时出片。和城ヶ崎海岸同一天。",
      guide: "大室山是伊豆的一座死火山，山顶像扣着的绿草帽，一圈步道能同时看山和海。它没有寺庙那么有名，意义在于：离开关东平原，日本还有火山列岛这一层地质故事。适合和城ヶ崎海岸放在同一天，当作河口湖的备选海边版。",
      xhs: ["伊豆大室山", "大室山缆车"],
      photo: "大室山",
      img: "img/spots/omuroyama-1.jpg",
      imgs: ["img/spots/omuroyama-1.jpg", "img/spots/omuroyama-2.jpg", "img/spots/omuroyama-3.jpg"],
      map: "Omuroyama Ito",
      lat: 34.9065,
      lng: 139.0967,
      day: 0,
      onMap: false,
      optional: true
    },
    {
      id: "jogasaki",
      region: "izu",
      area: "伊豆高原",
      group: "备选 · 静冈 · 伊豆",
      name: "城ヶ崎海岸",
      en: "Jōgasaki Coast",
      enter: "伊豆高原站巴士或出租。吊桥和海岸步道。和大室山同一天。",
      duration: "2–3 小时",
      note: "火山海岸、吊桥、海蚀。风大，穿防滑鞋。不要翻护栏。",
      guide: "城ヶ崎海岸是熔岩流入海形成的悬崖和吊桥，风大、浪响，和东京完全不是一种日本。名字容易和兵库的城崎温泉搞混，这里是静冈伊豆的海岸。第一次想看「海 + 地质」而不是湖和富士，就来这里。",
      xhs: ["城ヶ崎海岸", "城崎海岸吊桥"],
      photo: "伊豆半岛",
      img: "img/spots/jogasaki-2.jpg",
      imgs: ["img/spots/jogasaki-2.jpg", "img/spots/jogasaki-3.jpg"],
      map: "Jogasaki Coast Izu",
      lat: 34.8780,
      lng: 139.1160,
      day: 0,
      onMap: false,
      optional: true
    },
    {
      id: "odaiba",
      region: "tokyo",
      area: "台场",
      group: "备选 · 东京 · 台场",
      name: "台场海滨",
      en: "Odaiba Seaside",
      enter: "百合海鸥号或临海线。海滨公园免费。",
      duration: "1.5 小时",
      note: "自由女神、彩虹大桥同框。可替换东京塔那天的晚上。",
      guide: "台场是填海造出来的临海新城，有缩小版自由女神和彩虹大桥。1990 年代的未来感、周末家庭和湾岸夜景，是东京湾这一侧的休闲面。可以替换东京塔那天的晚上，但主线已经很满，不必当成必去。",
      xhs: ["台场自由女神", "台场海滨公园"],
      photo: "台场",
      img: "img/spots/odaiba-1.jpg",
      imgs: ["img/spots/odaiba-1.jpg", "img/spots/odaiba-3.jpg"],
      map: "Odaiba Seaside Park",
      lat: 35.6299,
      lng: 139.7752,
      day: 0,
      optional: true
    },
    {
      id: "rainbow",
      region: "tokyo",
      area: "台场",
      group: "备选 · 东京 · 台场",
      name: "彩虹大桥",
      en: "Rainbow Bridge",
      enter: "台场海滨或桥上步行道。外观免费。",
      duration: "40 分钟",
      note: "傍晚亮灯好看。和台场一起去，不要单独跑一趟。",
      guide: "彩虹大桥连接台场和港区，夜灯呈彩虹色，是东京湾的门户。桥本身是交通设施，被拍得多是因为它把海、车流和夜东京叠在一条线上。和台场海滨一起看就够，单独跑一趟不值得。",
      xhs: ["彩虹大桥夜景", "台场看彩虹大桥"],
      photo: "彩虹大桥",
      img: "img/spots/rainbow-1.jpg",
      imgs: ["img/spots/rainbow-1.jpg", "img/spots/rainbow-2.jpg", "img/spots/rainbow-3.jpg"],
      map: "Rainbow Bridge Tokyo",
      lat: 35.6366,
      lng: 139.7631,
      day: 0,
      optional: true
    },
    {
      id: "usj",
      region: "osaka",
      area: "大阪",
      group: "备选 · 大阪 · 这次不去",
      name: "大阪环球影城",
      en: "Universal Studios Japan",
      enter: "JR 梦洲站或环球城站。必须提前买指定日门票。从本町约 25–35 分钟。",
      duration: "一整天",
      note: "这次不去主题乐园。哈利波特园区留给以后单独排一天。",
      guide: "大阪环球影城是关西最强的主题乐园。这次行程偏城市和古都，不去乐园，DAY 02 改去奈良。",
      xhs: ["大阪环球影城", "USJ哈利波特"],
      photo: "环球影城",
      img: "img/spots/usj-1.jpg",
      imgs: ["img/spots/usj-1.jpg", "img/spots/usj-2.jpg", "img/spots/usj-3.jpg"],
      map: "Universal Studios Japan",
      lat: 34.6654,
      lng: 135.4323,
      day: 0,
      optional: true,
      onMap: false
    },
    {
      id: "kobe-port-tower",
      region: "kobe",
      area: "神户港",
      group: "备选 · 神户 · 不要塞进同一天",
      name: "神户港塔",
      en: "Kobe Port Tower",
      enter: "Harborland / 神户站步行。外观免费。登塔要票。",
      duration: "30–45 分钟",
      note: "DAY 02 神户备选已经从舞子走到三宫，不要再折去港塔。以后单独来 Harborland 再拍。",
      guide: "神户港塔是港城的红灯标，外形像鼓。它代表神户靠海吃饭的那一面，和舞子的悬索桥不是同一个尺度，一天里两座塔会赶路。",
      xhs: ["神户港塔", "神户港夜景"],
      photo: "神户港塔",
      map: "Kobe Port Tower",
      lat: 34.6826,
      lng: 135.1868,
      day: 0,
      optional: true
    },
    {
      id: "hyogo-art",
      region: "kobe",
      area: "HAT 神户",
      group: "备选 · 神户 · 不要塞进同一天",
      name: "兵库县立美术馆",
      en: "Hyogo Prefectural Museum of Art",
      enter: "JR 滩或阪神岩屋，再步行。要门票，看特展。",
      duration: "2–3 小时",
      note: "在三宫东边，和舞子相反。走神户备选就不要再加美术馆。",
      guide: "安藤忠雄设计的海边美术馆，适合单独排半天。和须磨沙滩、生田神社不是一条轴。",
      xhs: ["兵库县立美术馆", "安藤忠雄神户"],
      photo: "兵库县立美术馆",
      map: "Hyogo Prefectural Museum of Art",
      lat: 34.6994,
      lng: 135.2178,
      day: 0,
      optional: true
    },
    {
      id: "tetsujin",
      region: "kobe",
      area: "长田",
      group: "备选 · 神户 · 不要塞进同一天",
      name: "铁人28号",
      en: "Tetsujin 28",
      enter: "JR 新长田，若松公园。外观免费。须磨往三宫的车上会经过长田，想拍再下车。",
      duration: "20–30 分钟",
      note: "巨大机器人雕塑，拍一张就走。时间紧就坐过，不要为它打乱生田神社。",
      guide: "铁人28号是漫画里的巨人，立在震后重建的长田。它是神户的流行文化地标，不是必去神社。",
      xhs: ["铁人28号 神户", "新长田铁人"],
      photo: "铁人28号",
      map: "Tetsujin 28 Kobe",
      lat: 34.6564,
      lng: 135.147,
      day: 0,
      optional: true
    },
    {
      id: "anpanman",
      region: "kobe",
      area: "Harborland",
      group: "备选 · 神户 · 不要塞进同一天",
      name: "面包超人博物馆",
      en: "Kobe Anpanman Children's Museum",
      enter: "神户 Harborland。要指定门票，偏亲子。",
      duration: "2–3 小时",
      note: "儿童馆。这次两人摄影行程不去。不要和舞子、生田神社排在同一天。",
      guide: "面包超人家乡设定在神户，馆在 Harborland。适合带小孩，不适合这一周的主线。",
      xhs: ["神户面包超人博物馆"],
      photo: "神户面包超人儿童博物馆",
      map: "Kobe Anpanman Children's Museum",
      lat: 34.679,
      lng: 135.1875,
      day: 0,
      optional: true,
      onMap: false
    }
  ],
  days: [
    {
      id: 1,
      title: "大阪市区 citywalk",
      date: "10/06 周二",
      stay: "大阪本町彩鸿酒店",
      from: "大阪本町彩鸿酒店",
      where: "大阪城 → 四天王寺 → 通天阁 → 难波八阪 → 黑门 → 心斋桥 / 道顿堀夜景",
      path: "本町 → 大阪城公园 → 四天王寺 → 通天阁 / 新世界午饭 → 难波八阪狮子头 → 黑门市场 → 心斋桥药妆 → 道顿堀夜景 → 回本町",
      prep: [
        { item: "西瓜卡或 ICOCA", need: "必须。iPhone 用钱包 Suica；安卓落地买卡。关西也能刷", xhs: "iPhone西瓜卡" },
        { item: "大阪城、四天王寺、通天阁、难波八阪、黑门、道顿堀", need: "城和街道免费；四天王寺中心伽蓝约 300 日元。通天阁登顶约 900 日元，时间紧就拍外观" }
      ],
      beats: [
        { id: "d1a", time: "09:20", type: "commute", mode: "中央线", name: "本町 → 大阪城 · 约 15 分钟", lat: 34.6873, lng: 135.5262, cost: 200, detail: "本町坐中央线到森ノ宮。出站往公园走。拍西瓜卡。今天点多，城只拍外观。" },
        { id: "d1b", time: "09:40", type: "spot", name: "大阪城公园", spotId: "osaka-castle", cost: 0 },
        { id: "d1c", time: "11:00", type: "commute", mode: "谷町线", name: "大阪城 → 四天王寺 · 约 15 分钟", lat: 34.6544, lng: 135.5164, cost: 200, detail: "公园西边走到谷町四丁目，坐谷町线到四天王寺前夕陽ヶ丘（2 站）。不要绕去天王寺站商场。" },
        { id: "d1d", time: "11:20", type: "spot", name: "四天王寺", spotId: "shitennoji", cost: 300 },
        { id: "d1e", time: "12:20", type: "commute", mode: "步行", name: "四天王寺 → 新世界 · 约 15 分钟", lat: 34.6526, lng: 135.5064, cost: 0, detail: "往西走到新世界。串炸店中午排队，到了先点餐再拍塔。" },
        { id: "d1f", time: "12:40", type: "meal", name: "午饭 · 新世界串炸", lat: 34.6526, lng: 135.5064, xhs: "新世界串炸", cost: 1800, img: "img/spots/tsutenkaku-1.jpg", photo: "通天阁", detail: "串炸当正餐。人均大约 1500–2000 日元。不要吃到走不动。" },
        { id: "d1g", time: "13:35", type: "commute", mode: "步行", name: "串炸店 → 通天阁塔下 · 约 5 分钟", lat: 34.6526, lng: 135.5064, cost: 0, detail: "店就在塔旁边。时间紧就拍外观，不上展望台。" },
        { id: "d1h", time: "13:40", type: "spot", name: "通天阁 · 新世界", spotId: "tsutenkaku", cost: 0 },
        { id: "d1i", time: "14:30", type: "commute", mode: "步行", name: "通天阁 → 难波八阪 · 约 15 分钟", lat: 34.6614, lng: 135.4966, cost: 0, detail: "往西北走到难波八阪。Google 地图搜「难波八阪神社」。只背小包。" },
        { id: "d1j", time: "14:50", type: "spot", name: "难波八阪神社", spotId: "namba-yasaka", cost: 0 },
        { id: "d1k", time: "15:20", type: "commute", mode: "步行", name: "难波八阪 → 黑门市场 · 约 10 分钟", lat: 34.6654, lng: 135.5063, cost: 0, detail: "往东北走，约 800 米。摊位傍晚会陆续收，不要拖。" },
        { id: "d1l", time: "15:30", type: "spot", name: "黑门市场", spotId: "kuromon", cost: 800 },
        { id: "d1m", time: "16:30", type: "commute", mode: "步行", name: "黑门市场 → 心斋桥 · 约 10 分钟", lat: 34.6745, lng: 135.5013, cost: 0, detail: "沿堺筋或御堂筋往北走到心斋桥筋。" },
        { id: "d1n", time: "16:40", type: "spot", name: "心斋桥（药妆）", lat: 34.6745, lng: 135.5013, xhs: "心斋桥药妆", cost: 400, img: "img/spots/dotonbori-3.jpg", photo: "心斋桥", detail: "唐吉诃德、药妆。只买当天要用的，大件留东京最后一天。不要在白天拍固力果排队。" },
        { id: "d1o", time: "18:10", type: "commute", mode: "步行", name: "心斋桥 → 道顿堀 · 约 8 分钟", lat: 34.6687, lng: 135.5013, cost: 0, detail: "心斋桥筋往南走到运河。晚饭在道顿堀，不要折回药妆街。" },
        { id: "d1p", time: "18:20", type: "meal", name: "晚饭 · 道顿堀", lat: 34.6687, lng: 135.5013, xhs: "道顿堀晚饭", cost: 2200, img: "img/spots/dotonbori-1.jpg", photo: "道顿堀", detail: "章鱼烧当小吃，正餐找定食。人均大约 2000 日元。这是这次唯一一顿道顿堀正餐。" },
        { id: "d1q", time: "19:25", type: "commute", mode: "步行", name: "餐厅 → 固力果看板 · 约 5 分钟", lat: 34.6687, lng: 135.5013, cost: 0, detail: "沿运河走到戎桥。灯亮后再拍，不要站在桥中间挡路。" },
        { id: "d1r", time: "19:30", type: "spot", name: "道顿堀夜景", spotId: "dotonbori", cost: 0, detail: "灯亮后拍固力果和运河。昨晚若已拍过，今晚走侧机位即可。不要再逛第二遍心斋桥。" },
        { id: "d1s", time: "21:00", type: "commute", mode: "御堂筋线", name: "心斋桥 → 本町 · 约 5 分钟", lat: 34.68435, lng: 135.50275, cost: 180, detail: "心斋桥站坐御堂筋线北上一站到本町。明天主线去奈良；不想看鹿，右侧栏切到神户备选。" },
        { id: "d1t", time: "21:10", type: "hotel", name: "大阪本町彩鸿酒店", lat: 34.68435, lng: 135.50275, cost: 500 / 0.048, detail: "两人护照给前台。房费按大阪日均约 500 元计。不要再排大阪景点。" }
      ]
    },
    {
      id: 2,
      title: "奈良公园 · 奈良町",
      date: "10/07 周三",
      stay: "大阪本町彩鸿酒店",
      from: "大阪本町彩鸿酒店",
      where: "东大寺、奈良公园、奈良町",
      path: "本町 → 近铁奈良 → 东大寺 / 奈良公园 → 奈良町午饭 → 奈良町巷子 → 回本町晚饭",
      altMain: "奈良",
      prep: [
        { item: "本町 → 难波 → 近铁奈良", need: "御堂筋线到难波再换近铁。ICOCA / 西瓜卡可刷。近铁约 40 分钟", xhs: "难波去奈良近铁" },
        { item: "东大寺大佛殿门票", need: "现场买即可，约 800 日元；公园和鹿免费。奈良町巷子免费" },
        { item: "神户备选", need: "不想去奈良，右侧栏点 DAY 02「神户 · 舞子须磨」：舞子大桥 → 须磨 → 生田神社 → 三宫。不要再加港塔、铁人、面包超人馆" }
      ],
      beats: [
        { id: "d2a", time: "08:10", type: "commute", mode: "御堂筋线 + 近铁", name: "本町 → 近铁奈良 · 约 50 分钟", lat: 34.6845, lng: 135.8276, cost: 780, detail: "本町坐御堂筋线南下到难波，换近铁奈良线急行到近铁奈良。纸袋和零食收进包里，鹿会抢。" },
        { id: "d2b", time: "09:05", type: "commute", mode: "步行", name: "近铁奈良站 → 东大寺 · 约 15 分钟", lat: 34.6889, lng: 135.8398, cost: 0, detail: "出站往东进奈良公园。先买鹿仙贝，喂完再进大佛殿。" },
        { id: "d2c", time: "09:20", type: "spot", name: "奈良公园 · 东大寺", spotId: "nara", cost: 800 },
        { id: "d2d", time: "12:05", type: "commute", mode: "步行", name: "东大寺 → 奈良町 · 约 15 分钟", lat: 34.6775, lng: 135.8300, cost: 0, detail: "往西南走到奈良町。不要再折回公园喂鹿。" },
        { id: "d2e", time: "12:20", type: "meal", name: "午饭 · 奈良町", lat: 34.6775, lng: 135.8300, xhs: "奈良町午饭", cost: 1600, img: "img/spots/nara-3.jpg", photo: "奈良", detail: "町家定食或茶屋。人均大约 1500 日元。不要边走边吃。" },
        { id: "d2f", time: "13:35", type: "commute", mode: "步行", name: "午饭店 → 奈良町巷子 · 约 5 分钟", lat: 34.6775, lng: 135.8300, cost: 0, detail: "午饭就在巷子里，吃完继续往南走格子门。" },
        { id: "d2g", time: "13:40", type: "spot", name: "奈良町", spotId: "naramachi", cost: 0 },
        { id: "d2h", time: "16:20", type: "commute", mode: "步行", name: "奈良町 → 近铁奈良站 · 约 10 分钟", lat: 34.6845, lng: 135.8276, cost: 0, detail: "往北走回近铁奈良。不用卡末班。" },
        { id: "d2i", time: "16:40", type: "commute", mode: "近铁 + 御堂筋线", name: "近铁奈良 → 本町 · 约 50 分钟", lat: 34.68435, lng: 135.50275, cost: 780, detail: "近铁回难波，换御堂筋线到本町。行李留在酒店，明天去京都只背小包。" },
        { id: "d2j", time: "18:50", type: "meal", name: "晚饭 · 本町附近", lat: 34.68435, lng: 135.50275, xhs: "本町晚饭", cost: 1800, img: "img/spots/osaka-castle-1.jpg", photo: "本町", detail: "道顿堀昨晚已经吃过，今晚在本町附近定食即可。人均大约 1800 日元。不要再去固力果。" },
        { id: "d2k", time: "21:10", type: "commute", mode: "步行", name: "餐厅 → 酒店 · 约 5 分钟", lat: 34.68435, lng: 135.50275, cost: 0, detail: "本町站周边走回彩鸿酒店。" },
        { id: "d2l", time: "21:20", type: "hotel", name: "大阪本町彩鸿酒店", lat: 34.68435, lng: 135.50275, cost: 500 / 0.048, detail: "还住本町。明天京都整天，晚上回大阪。后天清早关西飞成田。" }
      ],
      alts: [
        {
          id: "kobe",
          tab: "神户",
          title: "神户 · 舞子须磨",
          where: "JR 海上列车去舞子，明石海峡大桥、须磨海岸、生田神社、三宫晚饭",
          path: "本町 → JR 神户线去舞子（靠左看海）→ 明石海峡大桥 → 须磨海岸午饭 → 三宫生田神社 → 三宫购物 → CoCo 一番屋 → 回本町",
          prep: [
            { item: "本町 → 梅田 → JR 舞子", need: "御堂筋线到梅田进大阪站，坐新快速往姬路，约 40–50 分钟到舞子。靠左坐看海", xhs: "JR神户线 舞子" },
            { item: "舞子海上步道", need: "现场买，平日约 250 日元。10/07 周三有开。9:00 开门，约 09:30 到刚好", xhs: "舞子海上步道" },
            { item: "不要再加的点", need: "港塔、兵库县立美术馆、铁人28号、面包超人馆不要塞进这一天。铁人在须磨→三宫车上经过，想拍再临时下车" }
          ],
          beats: [
            { id: "d2kobe-a", time: "08:20", type: "commute", mode: "御堂筋线 + JR 神户线", name: "本町 → 舞子 · 约 55 分钟", lat: 34.6344, lng: 135.0339, cost: 760, detail: "本町坐御堂筋线到梅田，进大阪站坐新快速往姬路，在「舞子」下。靠左边坐，海在南侧，这段常被叫海上列车。" },
            { id: "d2kobe-b", time: "09:20", type: "commute", mode: "步行", name: "舞子站 → 海上步道 · 约 5 分钟", lat: 34.6372, lng: 135.0217, cost: 0, detail: "出站往南，桥就在眼前。去舞子海上步道入口，不要走错去山阳舞子公园站方向绕远。" },
            { id: "d2kobe-c", time: "09:30", type: "spot", name: "明石海峡大桥 · 舞子", spotId: "maiko", cost: 250, detail: "玻璃观景台在步道里。恐高走旁边。外拍桥塔即可，11:20 前离开去须磨。" },
            { id: "d2kobe-d", time: "11:25", type: "commute", mode: "JR 神户线", name: "舞子 → 须磨 · 约 8 分钟", lat: 34.6423, lng: 135.1128, cost: 190, detail: "原线往大阪方向坐两站到须磨。不用换车。" },
            { id: "d2kobe-e", time: "11:40", type: "spot", name: "须磨海岸", spotId: "suma", cost: 0 },
            { id: "d2kobe-f", time: "12:30", type: "meal", name: "午饭 · 须磨", lat: 34.6423, lng: 135.1128, xhs: "须磨午饭", cost: 1000, img: "img/spots/suma-1.jpg", photo: "须磨海岸", detail: "海边轻食或便利店即可。人均大约 1000 日元。正餐留三宫的 CoCo。不要拖到下午。" },
            { id: "d2kobe-g", time: "13:25", type: "commute", mode: "JR 神户线", name: "须磨 → 三宫 · 约 15 分钟", lat: 34.6945, lng: 135.1951, cost: 200, detail: "往大阪方向坐到三宫。经过长田：铁人28号在若松公园，想拍就下车；时间紧坐过，去生田神社。" },
            { id: "d2kobe-h", time: "13:50", type: "commute", mode: "步行", name: "三宫 → 生田神社 · 约 8 分钟", lat: 34.6953, lng: 135.1887, cost: 0, detail: "三宫站北口往西北走。Google 地图搜「生田神社」。" },
            { id: "d2kobe-i", time: "14:00", type: "spot", name: "生田神社", spotId: "ikuta", cost: 800, detail: "鸟居、御守、小熊绘马。参拜后买一个御守即可，不必把货架搬空。" },
            { id: "d2kobe-j", time: "15:10", type: "commute", mode: "步行", name: "生田神社 → 三宫 · 约 8 分钟", lat: 34.6932, lng: 135.1955, cost: 0, detail: "走回三宫站周边。去唐吉诃德补货，不要折去 Harborland 港塔。" },
            { id: "d2kobe-k", time: "15:20", type: "spot", name: "三宫购物", spotId: "sannomiya", cost: 400 },
            { id: "d2kobe-l", time: "18:00", type: "meal", name: "晚饭 · CoCo 一番屋（三宫）", lat: 34.6937, lng: 135.1948, xhs: "CoCo一番屋 三宫", cost: 1100, img: "img/spots/sannomiya-1.jpg", photo: "三宫", detail: "按辣度点咖喱，可加咖喱包。人均大约 1000–1300 日元。这顿当正餐，不要再跑回大阪找店。" },
            { id: "d2kobe-m", time: "19:20", type: "commute", mode: "JR + 御堂筋线", name: "三宫 → 本町 · 约 45 分钟", lat: 34.68435, lng: 135.50275, cost: 590, detail: "JR 新快速到大阪站，换御堂筋线到本町。明天京都整天，只背小包。" },
            { id: "d2kobe-n", time: "20:10", type: "hotel", name: "大阪本町彩鸿酒店", lat: 34.68435, lng: 135.50275, cost: 500 / 0.048, detail: "还住本町。明天京都整天，晚上回大阪。后天清早关西飞成田。" }
          ]
        }
      ]
    },
    {
      id: 3,
      title: "京都 · 伏见清水",
      date: "10/08 周四",
      stay: "大阪本町彩鸿酒店",
      from: "大阪本町彩鸿酒店",
      where: "伏见稻荷、清水寺、二年坂，晚上回大阪",
      path: "本町 → 京都站 → 伏见稻荷 → 京阪去清水 → 二年坂午饭 → 清水寺 → 步行到祇园晚饭 → 京都站回本町",
      prep: [
        { item: "伏见稻荷、二年坂", need: "神社免费；清水寺本堂现场买票。今晚回大阪，不必赶飞机", xhs: "伏见稻荷千本鸟居" },
        { item: "行李", need: "大件留本町酒店。只背小包去京都，不用寄物柜" },
        { item: "明天机票", need: "已订 10/09 07:45 关西 → 成田，09:15 到。护照、登机牌今晚装随身包。明早约 04:50 退房", xhs: "南海电车关西机场" }
      ],
      beats: [
        { id: "d3a", time: "08:00", type: "commute", mode: "御堂筋线 + JR", name: "本町 → 京都站 · 约 45 分钟", lat: 34.9858, lng: 135.7588, cost: 580, detail: "本町坐御堂筋线北上到梅田，出站进大阪站，坐新快速到京都。行李留酒店，只背小包。" },
        { id: "d3b", time: "08:55", type: "commute", mode: "JR 奈良线", name: "京都站 → 稻荷 · 约 5 分钟", lat: 34.9671, lng: 135.7727, cost: 150, detail: "JR 奈良线一站到稻荷。出站就是伏见稻荷。" },
        { id: "d3c", time: "09:05", type: "spot", name: "伏见稻荷大社", spotId: "fushimi", cost: 0, detail: "千本鸟居可以多走一段。11:30 前下山即可，不必硬登顶。" },
        { id: "d3d", time: "11:40", type: "commute", mode: "京阪 + 步行", name: "伏见稻荷 → 清水寺 · 约 40 分钟", lat: 34.9948, lng: 135.7850, cost: 240, detail: "神社前坐京阪到清水五条，再沿清水道步行上山约 15 分钟。巴士人多就别硬挤。" },
        { id: "d3e", time: "12:30", type: "meal", name: "午饭 · 二年坂", lat: 34.9950, lng: 135.7838, xhs: "二年坂午饭", cost: 1600, img: "img/spots/kiyomizu-1.jpg", photo: "清水寺", detail: "坡道上小吃多。这顿当正餐。人均大约 1500 日元。" },
        { id: "d3f", time: "13:25", type: "commute", mode: "步行", name: "二年坂 → 清水寺 · 约 5 分钟", lat: 34.9948, lng: 135.7850, cost: 0, detail: "沿坡道走到山门。午饭已经在坡上，不用再找店。" },
        { id: "d3g", time: "13:30", type: "spot", name: "清水寺 · 二年坂", spotId: "kiyomizu", cost: 400, detail: "舞台和坡道各留一会儿。不用赶飞机，16:30 前离开即可。" },
        { id: "d3h", time: "16:40", type: "commute", mode: "步行", name: "二年坂 → 祇园 · 约 20 分钟", lat: 35.0037, lng: 135.7750, cost: 0, detail: "沿二年坂、产宁坂走到祇园、花见小路。人多就拍照离开，不要进私人小路。" },
        { id: "d3i", time: "17:50", type: "meal", name: "晚饭 · 祇园", lat: 35.0037, lng: 135.7750, xhs: "祇园晚饭", cost: 2200, img: "img/spots/kiyomizu-2.jpg", photo: "清水寺", detail: "祇园定食即可。人均大约 2000 日元。吃完去京都站坐 JR 回大阪。" },
        { id: "d3j", time: "19:00", type: "commute", mode: "巴士", name: "祇园 → 京都站 · 约 20 分钟", lat: 34.9858, lng: 135.7588, cost: 230, detail: "四条通坐市巴士到京都站。Google 地图搜「京都駅」。" },
        { id: "d3k", time: "19:20", type: "commute", mode: "JR + 御堂筋线", name: "京都站 → 本町 · 约 45 分钟", lat: 34.68435, lng: 135.50275, cost: 580, detail: "新快速到大阪站，换御堂筋线到本町。明天清早去关西机场，不要去伊丹。" },
        { id: "d3l", time: "21:00", type: "hotel", name: "大阪本町彩鸿酒店", lat: 34.68435, lng: 135.50275, cost: 500 / 0.048, detail: "大阪最后一晚。今晚早睡，04:40 起床。护照、充电宝、登机牌放随身包。退房约 04:50。" }
      ]
    },
    {
      id: 4,
      title: "关西飞成田 · 浅草",
      date: "10/09 周五",
      stay: "MW Hotel（南千住）",
      from: "大阪本町彩鸿酒店退房",
      where: "07:45 关西飞成田，白天浅草、傍晚晴空塔、晚上秋叶原",
      path: "本町退房 → 打车难波 → 南海去关西 → 07:45 飞成田 → Skyliner 到南千住放行李 → 浅草午饭 → 晴空塔傍晚 → 秋叶原 → 回酒店办入住",
      prep: [
        { item: "关西 → 成田机票", need: "已订 10/09 07:45–09:15，KIX→NRT。国内航班也要带护照。航司 App 提前值机", xhs: "关西机场国内线" },
        { item: "南海空港急行 05:15", need: "本町御堂筋线南下首班大约 05:19，赶不上这班。04:55 打车去南海难波。错过就改 05:28 那班", xhs: "南海电车关西机场" },
        { item: "晴空塔天望甲板指定时段票", need: "官网买 10/09 傍晚场（约 16:30–17:30 入场），看蓝调夜景", xhs: "东京晴空塔门票" },
        { item: "MW Hotel 寄行李", need: "入住多半 15:00 才开始。提前告诉前台大约 11:00 到，先寄放行李，晚上再办入住" }
      ],
      beats: [
        { id: "d4a", time: "04:50", type: "hotel", name: "大阪本町彩鸿酒店退房", lat: 34.68435, lng: 135.50275, checkout: true, detail: "04:40 起床。钥匙交给前台。护照、登机牌、充电宝放随身包。不要等到 10:00。" },
        { id: "d4b", time: "04:55", type: "commute", mode: "出租车", name: "本町 → 南海难波 · 约 10 分钟", lat: 34.6634, lng: 135.5018, cost: 1200, share: true, detail: "去「南海难波」不是地铁难波。御堂筋线南下首班大约 05:19，赶不上 05:15 空港急行。行李放后备箱。" },
        { id: "d4c", time: "05:15", type: "commute", mode: "南海空港急行", name: "难波 → 关西机场 · 约 45 分钟", lat: 34.4343, lng: 135.2441, cost: 970, detail: "三楼北改札进，5 / 6 号月台。看车头是「空港急行 / 关西空港」。IC 卡可拍。错过就改 05:28 那班。" },
        { id: "d4d", time: "06:05", type: "commute", mode: "步行", name: "关西机场值机 · 安检", lat: 34.4343, lng: 135.2441, cost: 0, detail: "国内线仍要护照。先托运行李再过安检。看登机牌确认航站楼。07:45 起飞，不要在到达层耗。" },
        { id: "d4e", time: "06:25", type: "meal", name: "早饭 · 关西机场", lat: 34.4343, lng: 135.2441, xhs: "关西机场早饭", cost: 1000, img: "img/spots/osaka-castle-1.jpg", photo: "大阪", detail: "过安检后再吃。人均大约 1000 日元。不要在本町慢慢吃早饭。" },
        { id: "d4f", time: "07:45", type: "commute", mode: "飞机", name: "关西 → 成田 · 07:45–09:15", lat: 35.7720, lng: 140.3929, cost: 14000, detail: "已订。飞行约 90 分钟。机上可看富士，看天气。落地走国内到达，取托运行李。不要出国际到达。" },
        { id: "d4g", time: "09:50", type: "commute", mode: "Skyliner", name: "成田 → 日暮里 · 约 40 分钟", lat: 35.7278, lng: 139.7714, cost: 2600, detail: "取完行李去京成 Skyliner。指定席要另买票，西瓜卡不够。约 10:00 那班。没有票就上野换成田特快。" },
        { id: "d4h", time: "10:45", type: "commute", mode: "常磐线", name: "日暮里 → 南千住 · 约 5 分钟", lat: 35.7336, lng: 139.7938, cost: 150, detail: "JR 常磐线一站到南千住。西口出站步行约 5 分钟到酒店。" },
        { id: "d4i", time: "10:55", type: "hotel", name: "MW Hotel 寄放行李", lat: 35.7336, lng: 139.7938, cost: 0, detail: "东京都荒川区南千住5-31-11。入住多半 15:00 才开始，先寄行李。两人护照给前台。今晚再办入住。" },
        { id: "d4j", time: "11:20", type: "commute", mode: "筑波快线", name: "南千住 → 浅草 · 约 5 分钟", lat: 35.7111, lng: 139.7964, cost: 200, detail: "筑波快线一站到浅草。拍西瓜卡。今天上午到，浅草不用赶夜场。" },
        { id: "d4k", time: "11:30", type: "spot", name: "雷门", spotId: "kaminarimon", cost: 0 },
        { id: "d4l", time: "11:50", type: "commute", mode: "步行", name: "雷门 → 仲见世 · 约 2 分钟", lat: 35.7117, lng: 139.7966, cost: 0, detail: "穿过雷门就是仲见世商店街。" },
        { id: "d4m", time: "11:55", type: "spot", name: "仲见世商店街", spotId: "nakamise", cost: 600 },
        { id: "d4n", time: "12:30", type: "commute", mode: "步行", name: "仲见世 → 浅草寺 · 约 3 分钟", lat: 35.7148, lng: 139.7967, cost: 0, detail: "走到头就是宝藏门和本堂。" },
        { id: "d4o", time: "12:35", type: "spot", name: "浅草寺", spotId: "sensoji", cost: 0 },
        { id: "d4p", time: "13:30", type: "meal", name: "午饭 · 浅草", lat: 35.7119, lng: 139.7964, xhs: "浅草午饭", cost: 1600, img: "img/spots/sensoji-1.jpg", photo: "浅草寺", detail: "仲见世或雷门附近定食即可。人均大约 1500 日元。吃完沿隅田川往吾妻桥慢慢走，不要提前上塔。" },
        { id: "d4q", time: "16:10", type: "commute", mode: "步行", name: "浅草 → 晴空塔 · 约 20 分钟", lat: 35.7101, lng: 139.8107, cost: 0, detail: "过吾妻桥，沿隅田川走到押上。腿累再改坐浅草线或银座线到押上。对一下傍晚入场时段。" },
        { id: "d4r", time: "16:40", type: "spot", name: "东京晴空塔", spotId: "skytree", cost: 2100, detail: "10 月日落大约 17:15，傍晚场看蓝调转夜景。第一次去天望甲板够用。" },
        { id: "d4s", time: "18:50", type: "commute", mode: "半藏门线 + 日比谷线", name: "押上 → 秋叶原 · 约 15 分钟", lat: 35.6984, lng: 139.7731, cost: 180, detail: "押上坐半藏门线到水天宫前，换日比谷线到秋叶原。晚上灯更亮。" },
        { id: "d4t", time: "19:10", type: "spot", name: "秋叶原", spotId: "akihabara", cost: 0 },
        { id: "d4u", time: "19:35", type: "commute", mode: "步行", name: "电器街 → 晚饭店 · 约 5 分钟", lat: 35.6986, lng: 139.7738, cost: 0, detail: "中央通两侧都有拉面、定食。不要跑去远的商场。" },
        { id: "d4v", time: "19:40", type: "meal", name: "晚饭 · 秋叶原", lat: 35.6986, lng: 139.7738, xhs: "秋叶原晚饭", cost: 1600, img: "img/spots/akihabara-1.jpg", photo: "秋叶原", detail: "拉面或定食即可。人均大约 1500 日元。" },
        { id: "d4w", time: "20:50", type: "commute", mode: "日比谷线", name: "秋叶原 → 南千住 · 约 12 分钟", lat: 35.7336, lng: 139.7938, cost: 180, detail: "日比谷线直达南千住。西口出站步行回酒店。" },
        { id: "d4x", time: "21:10", type: "hotel", name: "MW Hotel 办理入住", lat: 35.7336, lng: 139.7938, cost: 600 / 0.048, detail: "晚上再办入住。今晚起住 3 晚。护照给前台。回房间休息。" }
      ]
    },
    {
      id: 5,
      title: "涩谷 · SKY 夜景",
      date: "10/10 周六",
      stay: "MW Hotel（南千住）",
      from: "MW Hotel（南千住）",
      where: "明治神宫、原宿、涩谷路口、东京塔亮灯、SHIBUYA SKY 夜景",
      path: "南千住 → 原宿明治神宫 → 竹下通 / 表参道 → 涩谷路口 → 东京塔亮灯 → 回涩谷上 SKY → 回南千住",
      prep: [
        { item: "SHIBUYA SKY 指定时段票", need: "必须官网提前买 10/10 晚间入场，周六夜几乎买不到当日票", xhs: "SHIBUYA SKY门票" },
        { item: "明治神宫、竹下通、表参道、涩谷路口", need: "免费，不用预约" },
        { item: "东京塔外观", need: "芝公园、增上寺免费拍亮灯；今晚不上塔，要赶回涩谷" },
        { item: "薄外套", need: "SKY 屋顶风大，塔下也会凉" }
      ],
      beats: [
        { id: "d5a", time: "08:50", type: "commute", mode: "日比谷线 + 山手线", name: "南千住 → 原宿 · 约 35 分钟", lat: 35.6702, lng: 139.7027, cost: 280, detail: "日比谷线到上野，换山手线到原宿，出明治神宫口。比住新宿多大约半小时，早一点出门。" },
        { id: "d5b", time: "09:30", type: "spot", name: "明治神宫", spotId: "meiji", cost: 0 },
        { id: "d5c", time: "10:50", type: "commute", mode: "步行", name: "明治神宫 → 竹下通 · 约 10 分钟", lat: 35.6705, lng: 139.7064, cost: 0, detail: "原路走回原宿站，过桥就是竹下通。拍得慢就丢掉竹下通，不要丢掉晚上 SKY。" },
        { id: "d5d", time: "11:00", type: "spot", name: "竹下通", spotId: "takeshita", cost: 800 },
        { id: "d5e", time: "11:50", type: "commute", mode: "步行", name: "竹下通 → 原宿午饭 · 约 8 分钟", lat: 35.6688, lng: 139.7068, cost: 0, detail: "走到表参道口找定食。可丽饼只当垫饥。" },
        { id: "d5f", time: "12:00", type: "meal", name: "午饭 · 原宿 / 表参道", lat: 35.6688, lng: 139.7068, xhs: "原宿午饭", cost: 1600, img: "img/spots/omotesando-1.jpg", photo: "表参道", detail: "可丽饼当垫饥的话，正餐去表参道点定食。人均大约 1500 日元。" },
        { id: "d5g", time: "13:10", type: "commute", mode: "步行", name: "午饭店 → 表参道 · 约 8 分钟", lat: 35.6652, lng: 139.7124, cost: 0, detail: "沿表参道往青山方向走。" },
        { id: "d5h", time: "13:20", type: "spot", name: "表参道", spotId: "omotesando", cost: 0 },
        { id: "d5i", time: "14:20", type: "commute", mode: "银座线", name: "表参道 → 涩谷 · 约 10 分钟", lat: 35.6595, lng: 139.7004, cost: 170, detail: "表参道站坐银座线一站到涩谷。" },
        { id: "d5j", time: "14:40", type: "spot", name: "涩谷十字路口 · 中心街", spotId: "shibuya", cost: 0, detail: "先在地面拍路口和八公。晚上还要再回来上 SKY，这里不要耗太久。" },
        { id: "d5k", time: "16:00", type: "commute", mode: "银座线 + 步行", name: "涩谷 → 东京塔 · 约 20 分钟", lat: 35.6586, lng: 139.7454, cost: 220, detail: "涩谷坐银座线到虎ノ門，再步行到增上寺、芝公园。尽量 16:20 前到。" },
        { id: "d5l", time: "16:30", type: "spot", name: "东京塔亮灯", spotId: "tokyo-tower", cost: 0, detail: "增上寺山门框东京塔，再去芝公园拍全塔。不上展望台。17:40 前离开，赶回涩谷。" },
        { id: "d5m", time: "17:50", type: "commute", mode: "JR 山手线", name: "浜松町 → 涩谷 · 约 20 分钟", lat: 35.6584, lng: 139.7022, cost: 220, detail: "芝公园走到浜松町，坐山手线到涩谷。对一下 SKY 入场时段，迟到可能作废。" },
        { id: "d5n", time: "18:20", type: "meal", name: "晚饭 · 涩谷", lat: 35.6590, lng: 139.7015, xhs: "涩谷晚饭", cost: 2200, img: "img/spots/shibuya-2.jpg", photo: "涩谷", detail: "在涩谷吃，不要跑远。人均大约 2000 日元。吃完去 SKY。" },
        { id: "d5o", time: "19:30", type: "commute", mode: "步行", name: "晚饭店 → SHIBUYA SKY · 约 8 分钟", lat: 35.6584, lng: 139.7022, cost: 0, detail: "去涩谷 Scramble Square 14 楼检票。对一下预约时段。" },
        { id: "d5p", time: "19:40", type: "spot", name: "SHIBUYA SKY 夜景", spotId: "shibuya-sky", cost: 2500 },
        { id: "d5q", time: "21:40", type: "commute", mode: "山手线 + 日比谷线", name: "涩谷 → 南千住 · 约 40 分钟", lat: 35.7336, lng: 139.7938, cost: 280, detail: "山手线到上野，换日比谷线到南千住。屋顶风大，回酒店就休息。" },
        { id: "d5r", time: "22:20", type: "hotel", name: "MW Hotel", lat: 35.7336, lng: 139.7938, cost: 600 / 0.048, detail: "还住南千住。明天都心，日比谷线可直达筑地、银座。周日银座常有步行者天国。" }
      ]
    },
    {
      id: 6,
      title: "筑地 · 银座 · 皇居",
      date: "10/11 周日",
      stay: "MW Hotel（南千住）",
      from: "MW Hotel（南千住）",
      where: "筑地、银座步行者天国、皇居、东京站",
      path: "南千住 → 筑地早饭 → 银座 → 皇居二重桥 → 东京站 → 上野晚饭 → 回南千住",
      prep: [
        { item: "筑地、银座、皇居外苑、东京站外观", need: "免费逛" },
        { item: "银座周日步行者天国", need: "今天周日，中央通白天常封路，适合慢慢拍" }
      ],
      beats: [
        { id: "d6a", time: "08:10", type: "commute", mode: "日比谷线", name: "南千住 → 筑地 · 约 25 分钟", lat: 35.6654, lng: 139.7707, cost: 220, detail: "日比谷线直达筑地。去场外市场，不要去丰洲。" },
        { id: "d6b", time: "08:40", type: "spot", name: "筑地场外市场", spotId: "tsukiji", cost: 0 },
        { id: "d6c", time: "08:45", type: "commute", mode: "步行", name: "市场 → 寿司店 · 约 3 分钟", lat: 35.6652, lng: 139.7704, cost: 0, detail: "场外巷子里找寿司或海鲜丼。先问能不能拍照。" },
        { id: "d6d", time: "08:50", type: "meal", name: "早饭 · 筑地寿司 / 海鲜丼", lat: 35.6652, lng: 139.7704, xhs: "筑地早饭 寿司", cost: 2800, img: "img/spots/tsukiji-1.jpg", photo: "筑地市场", detail: "这顿当早午饭。人均 2500–4000 日元。" },
        { id: "d6e", time: "10:40", type: "commute", mode: "步行", name: "筑地 → 银座 · 约 15 分钟", lat: 35.6712, lng: 139.7649, cost: 0, detail: "沿晴海通往西走。今天周日，中央通常有步行者天国。" },
        { id: "d6f", time: "11:00", type: "spot", name: "银座", spotId: "ginza", cost: 0 },
        { id: "d6g", time: "13:00", type: "commute", mode: "有乐町线", name: "银座一丁目 → 樱田门 · 约 10 分钟", lat: 35.6802, lng: 139.7544, cost: 170, detail: "走到银座一丁目，坐有乐町线一站到樱田门。出站就是皇居外苑。人少也可以沿中央通步行约 20 分钟。" },
        { id: "d6h", time: "13:20", type: "spot", name: "皇居外苑 · 二重桥", spotId: "imperial", cost: 0 },
        { id: "d6i", time: "14:20", type: "commute", mode: "步行", name: "二重桥 → 东京站 · 约 12 分钟", lat: 35.6812, lng: 139.7671, cost: 0, detail: "沿行幸通对着红砖车站走。" },
        { id: "d6j", time: "14:40", type: "spot", name: "东京站丸之内", spotId: "tokyo-station", cost: 0 },
        { id: "d6k", time: "17:20", type: "commute", mode: "山手线", name: "东京站 → 上野 · 约 8 分钟", lat: 35.7138, lng: 139.7773, cost: 170, detail: "山手线或京浜东北到上野。晚饭在上野吃，不要先回酒店。" },
        { id: "d6l", time: "19:00", type: "meal", name: "晚饭 · 上野", lat: 35.7138, lng: 139.7773, xhs: "上野晚饭", cost: 2500, img: "img/spots/sensoji-1.jpg", photo: "上野", detail: "上野站周边定食即可。不要专门跑去歌舞伎町。连锁店更省事。" },
        { id: "d6m", time: "20:20", type: "commute", mode: "日比谷线", name: "上野 → 南千住 · 约 10 分钟", lat: 35.7336, lng: 139.7938, cost: 180, detail: "日比谷线或 JR 常磐线到南千住。西口步行回酒店。" },
        { id: "d6n", time: "20:40", type: "hotel", name: "MW Hotel · 收拾行李", lat: 35.7336, lng: 139.7938, cost: 600 / 0.048, detail: "明天 10/12 周一 15:05 成田起飞。今晚买好手信。护照、充电宝放随身包。" }
      ]
    },
    {
      id: 7,
      title: "成田返程",
      date: "10/12 周一",
      stay: "回北京",
      from: "MW Hotel（南千住）",
      where: "早饭后去成田，15:05 起飞",
      path: "早退 → 日暮里 Skyliner 或上野成田特快 → 15:05 回国",
      prep: [
        { item: "回程机票 15:05 成田（NRT）", need: "已订。国际航班提前 4 小时到场，最晚 11:00 前到航站楼", xhs: "日暮里 Skyliner" },
        { item: "新宿御苑周一休园", need: "今天不要绕去新宿，也来不及上都厅" },
        { item: "液体、充电宝", need: "按登机规定装好。药妆昨天买完，今天不要再大采购" }
      ],
      beats: [
        { id: "d7a", time: "08:30", type: "hotel", name: "MW Hotel 退房", lat: 35.7336, lng: 139.7938, checkout: true, detail: "今天退房，不再计房费。行李自己带去成田。护照、登机牌、充电宝放随身包。" },
        { id: "d7b", time: "08:40", type: "commute", mode: "步行", name: "酒店 → 便利店 / 早饭 · 约 3 分钟", lat: 35.7336, lng: 139.7938, cost: 0, detail: "南千住站西口便利店即可。不要坐下来慢慢吃。" },
        { id: "d7c", time: "08:50", type: "meal", name: "早饭 · 便利店", lat: 35.7336, lng: 139.7938, xhs: "南千住早饭", cost: 800, img: "img/spots/tmg-2.jpg", photo: "上野", detail: "便利店饭团即可。" },
        { id: "d7d", time: "09:30", type: "commute", mode: "常磐线", name: "南千住 → 日暮里 · 约 5 分钟", lat: 35.7278, lng: 139.7714, cost: 150, detail: "JR 常磐线一站到日暮里。去京成 Skyliner 月台。" },
        { id: "d7e", time: "09:40", type: "commute", mode: "Skyliner", name: "日暮里 → 成田机场 · 约 45 分钟", lat: 35.7720, lng: 140.3929, cost: 2600, detail: "京成 Skyliner 到成田。没有票就上野换成田特快。行李放指定车厢。15:05 起飞，11:00 前必须到航站楼。" }
      ]
    }
  ]
};
