window.TRIP = {
  title: "日本六日",
  subtitle: "10 月 · 两人小白，偏摄影",
  route: "北京 → 东京新宿住 6 晚 → 一日河口湖拍富士 → 回北京",
  budget: {
    jpyToCny: 0.048,
    hotelNights: 6,
    hotelRoomJpy: 20000,
    hotelNote: "新宿商务酒店双床标间，一晚大约 2 万日元"
  },
  spots: [
    {
      id: "kaminarimon",
      region: "tokyo",
      area: "浅草",
      group: "DAY 01 · 东京 · 浅草",
      name: "雷门",
      en: "Kaminarimon",
      enter: "地铁银座线 / 浅草线「浅草」站步行约 5 分钟。免费，不用预约。",
      duration: "15–20 分钟",
      note: "大红灯笼是浅草第一张。人多时侧拍、等人流空隙。灯笼背面也有字，可以绕过去拍。",
      guide: "雷门是浅草寺的正门，也是很多人到东京后拍下的第一张「我到了」。门上那盏巨灯笼写着「雷门」，两侧是风神和雷神，保佑过路人平安。穿过这道门，才算走进江户留下来的庶民街区浅草——它不只是背景板，是整条参拜轴的起点。",
      xhs: ["浅草雷门拍照", "雷门灯笼机位"],
      photo: "雷门",
      img: "img/spots/kaminarimon-1.jpg",
      imgs: ["img/spots/kaminarimon-1.jpg", "img/spots/kaminarimon-2.jpg", "img/spots/kaminarimon-3.jpg"],
      map: "Kaminarimon Asakusa",
      lat: 35.7111,
      lng: 139.7964,
      day: 1
    },
    {
      id: "sensoji",
      region: "tokyo",
      area: "浅草",
      group: "DAY 01 · 东京 · 浅草",
      name: "浅草寺",
      en: "Sensō-ji",
      enter: "雷门穿过仲见世即到。寺院免费。正殿大约 6:00–17:00。",
      duration: "45–60 分钟",
      note: "宝藏门、五重塔、本堂都好看。进门洗手。抽签：大吉可带走，不好的系在架子上。上午侧光更干净。",
      guide: "浅草寺是东京最古老的寺院，供奉观音。传说渔民在隅田川捞到观音像，由此建寺，所以直到今天仍是普通人求平安、求学业的地方。香炉的烟、五重塔、本堂，是最典型的「下町」寺庙样子。第一次来日本，不妨在这里跟着旁边的人学一次参拜。",
      xhs: ["浅草寺拍照", "浅草寺五重塔", "浅草寺抽签"],
      photo: "浅草寺",
      img: "img/spots/sensoji-1.jpg",
      imgs: ["img/spots/sensoji-1.jpg", "img/spots/sensoji-2.jpg", "img/spots/sensoji-3.jpg"],
      map: "Senso-ji Asakusa Tokyo",
      lat: 35.7148,
      lng: 139.7967,
      day: 1
    },
    {
      id: "nakamise",
      region: "tokyo",
      area: "浅草",
      group: "DAY 01 · 东京 · 浅草",
      name: "仲见世商店街",
      en: "Nakamise-dōri",
      enter: "雷门到宝藏门之间。公共街道，免费。",
      duration: "30 分钟",
      note: "人形烧、扇子、和风小物。站路边吃，不要边走边吃挡路。",
      guide: "仲见世是雷门到浅草寺之间那条古老商店街，江户时代就是给进香人准备的。人形烧、扇子、小物排在两侧，意义不在买多少，而在于你走在一条还活着的参拜道上——寺庙、小生意和游客叠在同一条轴线上，这就是浅草。",
      xhs: ["仲见世商店街", "浅草人形烧"],
      photo: "仲见世",
      img: "img/spots/nakamise-1.jpg",
      imgs: ["img/spots/nakamise-1.jpg", "img/spots/nakamise-2.jpg"],
      map: "Nakamise-dori Asakusa",
      lat: 35.7119,
      lng: 139.7964,
      day: 1
    },
    {
      id: "skytree",
      region: "tokyo",
      area: "押上",
      group: "DAY 01 · 东京 · 浅草",
      name: "东京晴空塔",
      en: "Tokyo Skytree",
      enter: "浅草步行约 20 分钟，或地铁到押上。天望甲板建议官网买指定时段。",
      duration: "1.5–2 小时",
      note: "10 月能见度通常不错，晴天可能看到富士山。第一次去天望甲板够用。日落场更好看。",
      guide: "东京晴空塔 2012 年才亮相，是世界最高的自立式电波塔之一，也是东京向东看的新天际线。站上天望甲板，浅草、隅田川，运气好时连富士山都能放进同一张照片。它代表当代东京：用一座能被一眼认出来的塔，给这座巨大城市再做一个符号。",
      xhs: ["东京晴空塔展望台", "晴空塔看富士山"],
      photo: "东京晴空塔",
      img: "img/spots/skytree-1.jpg",
      imgs: ["img/spots/skytree-1.jpg", "img/spots/skytree-2.jpg", "img/spots/skytree-3.jpg"],
      map: "Tokyo Skytree",
      lat: 35.7101,
      lng: 139.8107,
      day: 1
    },
    {
      id: "akihabara",
      region: "tokyo",
      area: "秋叶原",
      group: "DAY 01 · 东京 · 秋叶原",
      name: "秋叶原",
      en: "Akihabara",
      enter: "JR 山手线秋叶原站。街道免费。电器店、动漫店晚上灯更亮。",
      duration: "1–1.5 小时",
      note: "中央通两侧广告牌很好拍。晚上霓虹更出片。店里有的不能拍，看告示。人多把包转到身前。",
      guide: "秋叶原从电器街长成御宅文化的门面。中央通两侧的灯牌、动漫店、女仆店招，是日本流行文化对外输出最密的一条街。晚上灯全亮，才是它真正的样子。第一次来不必强迫购物，顺着街道走、抬头拍广告墙，就能读懂东京的另一面。",
      xhs: ["秋叶原夜景", "秋叶原中央通拍照"],
      photo: "秋叶原",
      img: "img/spots/akihabara-1.jpg",
      imgs: ["img/spots/akihabara-1.jpg", "img/spots/akihabara-2.jpg", "img/spots/akihabara-3.jpg"],
      map: "Akihabara Chuo dori",
      lat: 35.6984,
      lng: 139.7731,
      day: 1
    },
    {
      id: "meiji",
      region: "tokyo",
      area: "原宿",
      group: "DAY 02 · 东京 · 原宿涩谷",
      name: "明治神宫",
      en: "Meiji Jingu",
      enter: "JR 原宿站明治神宫口。境内免费。黎明到日落。",
      duration: "1–1.5 小时",
      note: "进鸟居走两侧。森林和鸟居是原宿最干净的一张。参拜：鞠躬两次、拍手两次、再鞠躬。",
      guide: "明治神宫祭祀明治天皇与昭宪皇后，是东京正中心一片人造的深林。原宿再吵，一进鸟居就静下来。现代东京从明治维新长出来，神宫用森林把那段历史藏在时尚街区旁边。参拜很简单：鞠躬两次、拍手两次、再鞠躬，跟着旁边的人做即可。",
      xhs: ["明治神宫鸟居", "明治神宫参拜"],
      photo: "明治神宫",
      img: "img/spots/meiji-1.jpg",
      imgs: ["img/spots/meiji-1.jpg", "img/spots/meiji-2.jpg", "img/spots/meiji-3.jpg"],
      map: "Meiji Jingu Shrine",
      lat: 35.6764,
      lng: 139.6993,
      day: 2
    },
    {
      id: "takeshita",
      region: "tokyo",
      area: "原宿",
      group: "DAY 02 · 东京 · 原宿涩谷",
      name: "竹下通",
      en: "Takeshita Street",
      enter: "JR 原宿站竹下口对面。免费。",
      duration: "30–40 分钟",
      note: "年轻街拍、可丽饼。周末极挤，背包放身前。",
      guide: "竹下通是原宿的年轻街区，可丽饼、古着、街头时尚从这里传到全世界。它没有古迹，特色就是「此刻的东京年轻人怎么玩」。周末会挤到几乎走不动，适合快看、买个吃的，把时间留给旁边的神宫和表参道。",
      xhs: ["竹下通可丽饼", "原宿竹下通"],
      photo: "原宿",
      img: "img/spots/takeshita-1.jpg",
      imgs: ["img/spots/takeshita-1.jpg", "img/spots/takeshita-3.jpg"],
      map: "Takeshita Dori Harajuku",
      lat: 35.6705,
      lng: 139.7061,
      day: 2
    },
    {
      id: "omotesando",
      region: "tokyo",
      area: "表参道",
      group: "DAY 02 · 东京 · 原宿涩谷",
      name: "表参道",
      en: "Omotesandō",
      enter: "竹下通往南，或地铁表参道站。街道免费。",
      duration: "40 分钟",
      note: "10 月银杏开始转黄，建筑和橱窗好拍。比竹下通安静。",
      guide: "表参道原本是通往明治神宫的参拜大道，后来长成东京最讲究的林荫商业街。建筑、橱窗、银杏沿路排开。竹下通吵、表参道从容，两条街拼在一起，才是完整的原宿：一边是年轻人的现在，一边是参拜道变成的时髦。",
      xhs: ["表参道银杏", "表参道建筑"],
      photo: "表参道",
      img: "img/spots/omotesando-1.jpg",
      imgs: ["img/spots/omotesando-1.jpg", "img/spots/omotesando-2.jpg", "img/spots/omotesando-3.jpg"],
      map: "Omotesando Tokyo",
      lat: 35.6654,
      lng: 139.7123,
      day: 2
    },
    {
      id: "shibuya",
      region: "tokyo",
      area: "涩谷",
      group: "DAY 02 · 东京 · 原宿涩谷",
      name: "涩谷十字路口 · 中心街",
      en: "Shibuya Crossing & Center-gai",
      enter: "JR 涩谷站八公口。路口和中心街免费。",
      duration: "40–50 分钟",
      note: "绿灯时从人行道中间回头拍人潮。八公像很小，合影请快。晚上中心街霓虹更好看。",
      guide: "涩谷十字路口常被称为世界上最繁忙的人行横道。绿灯一亮，四面的人在路口中央交错，是东京密度和秩序同时存在的象征。旁边的忠犬八公像纪念那只等主人回家的秋田犬，也是最常用的碰头点。晚上再走进中心街，霓虹才真正铺开。",
      xhs: ["涩谷十字路口拍照", "涩谷中心街夜景", "忠犬八公像"],
      photo: "涩谷",
      img: "img/spots/shibuya-2.jpg",
      imgs: ["img/spots/shibuya-2.jpg", "img/spots/shibuya-1.jpg"],
      map: "Shibuya Crossing Tokyo",
      lat: 35.6595,
      lng: 139.7004,
      day: 2
    },
    {
      id: "tokyo-tower",
      region: "tokyo",
      area: "芝公园",
      group: "DAY 02 · 东京 · 港区",
      name: "东京塔",
      en: "Tokyo Tower",
      enter: "地铁赤羽桥站或神谷町站。塔下芝公园免费拍外观。上展望台要票，建议官网。",
      duration: "1–1.5 小时",
      note: "红白塔身白天、晚上都好拍。增上寺门框里套东京塔是经典机位。10 月日落大约 17:10，尽量赶上亮灯。",
      guide: "东京塔 1958 年建成，造型模仿埃菲尔铁塔，红白涂装是为了航空警示。很长一段时间里，它就是「东京」两个字的视觉符号，比晴空塔更有昭和味道。增上寺山门把塔框进去，等于把江户寺庙和战后铁塔叠在同一张画面里。",
      xhs: ["东京塔增上寺", "东京塔夜景拍照"],
      photo: "东京塔",
      img: "img/spots/tokyo-tower-1.jpg",
      imgs: ["img/spots/tokyo-tower-1.jpg", "img/spots/tokyo-tower-2.jpg", "img/spots/tokyo-tower-3.jpg"],
      map: "Tokyo Tower",
      lat: 35.6586,
      lng: 139.7454,
      day: 2
    },
    {
      id: "disneysea",
      region: "maihama",
      area: "舞浜",
      group: "DAY 03 · 千叶 · 舞浜",
      name: "东京迪士尼海洋",
      en: "Tokyo DisneySea",
      enter: "必须提前买指定日门票。JR 京叶线舞浜，再坐度假区线到海洋。现场不售票。",
      duration: "一整天",
      note: "地中海港湾、火山、夜晚水上秀比乐园更好拍。10 月平日比周末好排。下载官方 App。",
      guide: "东京迪士尼海洋是全世界独有的海洋主题迪士尼，七大港口围着地中海港湾，中央是一座假火山。它不是再做一个城堡乐园，而是把航海、冒险和夜景做成一整座舞台。对第一次来、又爱拍照的人，港湾的水和灯往往比设施本身更难忘。",
      xhs: ["迪士尼海洋地中海港湾", "东京迪士尼海洋拍照"],
      photo: "东京迪士尼海洋",
      img: "img/spots/disneysea-1.jpg",
      imgs: ["img/spots/disneysea-1.jpg", "img/spots/disneysea-2.jpg", "img/spots/disneysea-3.jpg"],
      map: "Tokyo DisneySea",
      lat: 35.6267,
      lng: 139.8851,
      day: 3
    },
    {
      id: "tsukiji",
      region: "tokyo",
      area: "筑地",
      group: "DAY 04 · 东京 · 都心",
      name: "筑地场外市场",
      en: "Tsukiji Outer Market",
      enter: "日比谷线筑地站。场外免费逛。内市场已迁丰洲，不要跑错。",
      duration: "1.5 小时（含早饭）",
      note: "海鲜颜色好拍，先问能不能拍。店小，两人拼桌常见。",
      guide: "筑地曾是世界最大的鱼市场。2018 年内市场迁去丰洲，场外市场还留在原地，寿司、海鲜丼、刀具店挤在巷子里。你在这里吃的是东京人对新鲜海产的执念，也是一层还没被商场替换掉的市井气味。记住：不要跑去丰洲找「老筑地」。",
      xhs: ["筑地场外市场寿司", "筑地早饭"],
      photo: "筑地市场",
      img: "img/spots/tsukiji-1.jpg",
      imgs: ["img/spots/tsukiji-1.jpg"],
      map: "Tsukiji Outer Market",
      lat: 35.6654,
      lng: 139.7707,
      day: 4
    },
    {
      id: "ginza",
      region: "tokyo",
      area: "银座",
      group: "DAY 04 · 东京 · 都心",
      name: "银座",
      en: "Ginza",
      enter: "筑地步行约 15 分钟。周日白天常有步行者天国。",
      duration: "1 小时",
      note: "和光钟楼是地标。晚上霓虹更好看。大件留到最后一天再买。",
      guide: "银座是东京最早的西式砖街之一，明治时期就代表「最时髦的日本」。和光钟楼、三越、步行者天国，是金钱、橱窗和礼仪同时很讲究的地方。不一定要买东西，顺着中央通走一段，就能感到这座城市把消费也做成了风景。",
      xhs: ["银座和光", "银座夜景"],
      photo: "银座",
      img: "img/spots/ginza-1.jpg",
      imgs: ["img/spots/ginza-1.jpg", "img/spots/ginza-2.jpg", "img/spots/ginza-3.jpg"],
      map: "Ginza Tokyo",
      lat: 35.6712,
      lng: 139.7649,
      day: 4
    },
    {
      id: "imperial",
      region: "tokyo",
      area: "千代田",
      group: "DAY 04 · 东京 · 都心",
      name: "皇居外苑 · 二重桥",
      en: "Imperial Palace Nijubashi",
      enter: "二重桥前站或樱田门站。外苑免费。",
      duration: "45 分钟",
      note: "拍双重桥和石墙即可。广场空旷，帽子有用。",
      guide: "皇居是天皇居住的地方，一般游客只到外苑和二重桥。双重拱桥、护城河和石墙，把「日本还有一个皇家中心」变成能看见的风景。广场空旷、天空很大，和浅草、涩谷完全相反——东京也有故意留白的一面。",
      xhs: ["皇居二重桥", "皇居外苑"],
      photo: "皇居",
      img: "img/spots/imperial-1.jpg",
      imgs: ["img/spots/imperial-1.jpg", "img/spots/imperial-2.jpg", "img/spots/imperial-3.jpg"],
      map: "Nijubashi Imperial Palace",
      lat: 35.6802,
      lng: 139.7544,
      day: 4
    },
    {
      id: "tokyo-station",
      region: "tokyo",
      area: "丸之内",
      group: "DAY 04 · 东京 · 都心",
      name: "东京站丸之内",
      en: "Tokyo Station Marunouchi",
      enter: "JR 东京站丸之内口。外观和 KITTE 屋顶免费。",
      duration: "40 分钟",
      note: "红砖车站是经典机位。KITTE 屋顶能拍全景。傍晚灯亮更好看。",
      guide: "东京站丸之内红砖站房由辰野金吾设计，1914 年启用，战后按原貌修复。它是日本铁路网的心脏，也是把欧洲车站美学搬进东京的纪念碑。KITTE 屋顶能看到完整立面，傍晚灯亮时最像明信片。",
      xhs: ["东京站丸之内", "KITTE屋顶东京站"],
      photo: "东京车站",
      img: "img/spots/station-1.jpg",
      imgs: ["img/spots/station-1.jpg", "img/spots/station-2.jpg", "img/spots/station-3.jpg"],
      map: "Tokyo Station Marunouchi",
      lat: 35.6812,
      lng: 139.7671,
      day: 4
    },
    {
      id: "shinkansen",
      region: "tokyo",
      area: "东京站",
      group: "DAY 04 · 东京 · 都心",
      name: "新干线（东京站拍车头）",
      en: "Shinkansen at Tokyo Station",
      enter: "东京站新干线口。进站台通常要车票或站台票。外观可在丸之内先拍车站。",
      duration: "20–30 分钟",
      note: "这次主线不去大阪，所以只在东京站看一眼车头，不当交通。真要坐新干线看风景，用伊豆备选那天（东京→热海）。",
      guide: "新干线 1964 年通车，是日本速度、准点和战后复兴的象征。车头那张「大嘴」照片，对很多人来说等于见过日本的火车。这次不坐去大阪，进站台看一眼就够；真要坐车看风景，留给伊豆备选那天的热海方向。",
      xhs: ["东京站新干线拍照", "N700S车头"],
      photo: "新干线",
      img: "img/spots/shinkansen-1.jpg",
      imgs: ["img/spots/shinkansen-1.jpg", "img/spots/shinkansen-2.jpg", "img/spots/shinkansen-3.jpg"],
      map: "Tokyo Station Shinkansen",
      lat: 35.6814,
      lng: 139.7660,
      day: 4
    },
    {
      id: "kawaguchiko",
      region: "fuji",
      area: "河口湖",
      group: "DAY 05 · 山梨 · 河口湖",
      name: "河口湖",
      en: "Lake Kawaguchi",
      enter: "新宿高速巴士约 1 小时 45 分到河口湖站。湖畔免费。",
      duration: "大半天",
      note: "10 月是拍富士的好季节，但不能保证一定看到山，看天气预报和云。北岸、大石公园倒影更稳。",
      guide: "河口湖是富士五湖里最容易从东京到达、也最好拍倒影的一座。湖、小镇、富士山，构成关东人最熟悉的「出城看山」线路。10 月空气相对干净，山是否露脸全看云。来这里不只是打卡富士，也是离开水泥东京一天，把节奏放慢。",
      xhs: ["河口湖拍富士山", "大石公园富士山"],
      photo: "河口湖",
      img: "img/spots/kawaguchiko-1.jpg",
      imgs: ["img/spots/kawaguchiko-1.jpg", "img/spots/kawaguchiko-2.jpg", "img/spots/kawaguchiko-3.jpg"],
      map: "Lake Kawaguchi",
      lat: 35.5170,
      lng: 138.7519,
      day: 5
    },
    {
      id: "fuji",
      region: "fuji",
      area: "河口湖",
      group: "DAY 05 · 山梨 · 河口湖",
      name: "富士山观景",
      en: "Mount Fuji View",
      enter: "河口湖一带多个观景点。新仓山浅间公园要爬台阶，天气好时塔和富士同框。",
      duration: "1–2 小时",
      note: "经典机位是五重塔 + 富士。周末人很多。云挡住就改拍湖和枫叶，不要死等。",
      guide: "富士山是日本最高峰，也是浮世绘和课本里的国家象征。河口湖这边最经典的构图在新仓山浅间公园：五重塔、树木，远处是雪顶。山在文化里很神圣，天气不好时不必死等——云本身也是富士的一部分。",
      xhs: ["新仓山浅间公园", "河口湖五重塔富士山"],
      photo: "富士山",
      img: "img/spots/fuji-2.jpg",
      imgs: ["img/spots/fuji-2.jpg", "img/spots/fuji-3.jpg", "img/spots/kawaguchiko-1.jpg"],
      map: "Arakurayama Sengen Park",
      lat: 35.5013,
      lng: 138.8016,
      day: 5
    },
    {
      id: "gyoen",
      region: "tokyo",
      area: "新宿",
      group: "备选 · 东京 · 新宿御苑",
      name: "新宿御苑",
      en: "Shinjuku Gyoen",
      enter: "新宿站东南口步行约 10 分钟。成人 500 日元。周一休园。",
      duration: "1–1.5 小时",
      note: "10/12 返程是周一，御苑休园，所以没排进第 6 天。想去就插到第 2 天或第 4 天的空档，不要和迪士尼、河口湖抢整天。",
      guide: "新宿御苑曾是江户大名宅邸，后来变成皇室花园，再向公众开放。日式、英式、法式庭园挨在一起，是新宿水泥森林里少有的大片绿地。周一休园，所以没排进返程那天。想去就插在市内某天的空档，慢慢走比赶点合适。",
      xhs: ["新宿御苑拍照", "新宿御苑周一休园"],
      photo: "新宿御苑",
      img: "img/spots/gyoen-1.jpg",
      imgs: ["img/spots/gyoen-1.jpg", "img/spots/gyoen-2.jpg", "img/spots/gyoen-3.jpg"],
      map: "Shinjuku Gyoen",
      lat: 35.6852,
      lng: 139.7100,
      day: 0,
      optional: true
    },
    {
      id: "tmg",
      region: "tokyo",
      area: "西新宿",
      group: "DAY 06 · 东京 · 新宿",
      name: "都厅展望室",
      en: "Tokyo Metropolitan Government Building",
      enter: "新宿西口步行约 10 分钟。免费，不用预约。",
      duration: "40 分钟",
      note: "免费夜景。看当天开南塔还是北塔。适合退房前或返程前的轻松收尾。",
      guide: "东京都厅是东京都政府办公楼，丹下健三设计，两座塔楼像哥特教堂。顶楼展望室免费，能看西边的富士和脚下的新宿。它代表「行政东京」：不是寺庙也不是商店街，而是这座超大城市如何被管理。退房后行李还在身上时，这是最省力的收尾。",
      xhs: ["都厅展望台夜景", "新宿都厅免费"],
      photo: "东京都厅",
      img: "img/spots/tmg-2.jpg",
      imgs: ["img/spots/tmg-2.jpg", "img/spots/tmg-3.jpg"],
      map: "Tokyo Metropolitan Government Building",
      lat: 35.6896,
      lng: 139.6917,
      day: 6
    },
    {
      id: "disneyland",
      region: "maihama",
      area: "舞浜",
      group: "备选 · 千叶 · 迪士尼乐园",
      name: "东京迪士尼乐园",
      en: "Tokyo Disneyland",
      enter: "和海洋是两个园，门票不能通用。可与第 3 天海洋对调，不要两天都排。",
      duration: "一整天",
      note: "城堡夜景好看。第一次去、又爱拍建筑和海景，主线选海洋；更想逛经典城堡就换乐园。",
      guide: "东京迪士尼乐园是亚洲第一座迪士尼，城堡、游行、万圣节都更「经典迪士尼」。和海洋是两个完全不同的园，票不能混用。主线选海洋是因为港湾更好拍；更想要城堡和童年符号，可以对调，但不要两天都排。",
      xhs: ["东京迪士尼城堡", "东京迪士尼万圣节"],
      photo: "东京迪士尼乐园",
      img: "img/spots/disneyland-1.jpg",
      imgs: ["img/spots/disneyland-1.jpg", "img/spots/disneyland-2.jpg", "img/spots/disneyland-3.jpg"],
      map: "Tokyo Disneyland",
      lat: 35.6329,
      lng: 139.8804,
      day: 0,
      optional: true
    },
    {
      id: "omuroyama",
      region: "izu",
      area: "伊豆高原",
      group: "备选 · 静冈 · 伊豆",
      name: "大室山",
      en: "Mount Ōmuro",
      enter: "新干线东京→热海，再伊豆急行到伊豆高原。上山坐缆车。可与河口湖对调，不要两天都去。",
      duration: "半天（含交通则一整天）",
      note: "草山像绿帽子，山顶一圈能看海。10 月天气好时出片。和城ヶ崎海岸同一天。",
      guide: "大室山是伊豆的一座死火山，山顶像扣着的绿草帽，一圈步道能同时看山和海。它没有寺庙那么有名，意义在于：离开关东平原，日本还有火山列岛这一层地质故事。适合和城ヶ崎海岸放在同一天，当作河口湖的备选海边版。",
      xhs: ["伊豆大室山", "大室山缆车"],
      photo: "大室山",
      img: "img/spots/omuroyama-1.jpg",
      imgs: ["img/spots/omuroyama-1.jpg", "img/spots/omuroyama-2.jpg", "img/spots/omuroyama-3.jpg"],
      map: "Omuroyama Ito",
      lat: 34.9065,
      lng: 139.0967,
      day: 0,
      optional: true
    },
    {
      id: "jogasaki",
      region: "izu",
      area: "伊豆高原",
      group: "备选 · 静冈 · 伊豆",
      name: "城ヶ崎海岸",
      en: "Jōgasaki Coast",
      enter: "伊豆高原站巴士或出租。吊桥和海岸步道。和大室山同一天。",
      duration: "2–3 小时",
      note: "火山海岸、吊桥、海蚀。风大，穿防滑鞋。不要翻护栏。",
      guide: "城ヶ崎海岸是熔岩流入海形成的悬崖和吊桥，风大、浪响，和东京完全不是一种日本。名字容易和兵库的城崎温泉搞混，这里是静冈伊豆的海岸。第一次想看「海 + 地质」而不是湖和富士，就来这里。",
      xhs: ["城ヶ崎海岸", "城崎海岸吊桥"],
      photo: "伊豆半岛",
      img: "img/spots/jogasaki-2.jpg",
      imgs: ["img/spots/jogasaki-2.jpg", "img/spots/jogasaki-3.jpg"],
      map: "Jogasaki Coast Izu",
      lat: 34.8780,
      lng: 139.1160,
      day: 0,
      optional: true
    },
    {
      id: "odaiba",
      region: "tokyo",
      area: "台场",
      group: "备选 · 东京 · 台场",
      name: "台场海滨",
      en: "Odaiba Seaside",
      enter: "百合海鸥号或临海线。海滨公园免费。",
      duration: "1.5 小时",
      note: "自由女神、彩虹大桥同框。可替换东京塔那天的晚上。",
      guide: "台场是填海造出来的临海新城，有缩小版自由女神和彩虹大桥。1990 年代的未来感、周末家庭和湾岸夜景，是东京湾这一侧的休闲面。可以替换东京塔那天的晚上，但主线已经很满，不必当成必去。",
      xhs: ["台场自由女神", "台场海滨公园"],
      photo: "台场",
      img: "img/spots/odaiba-1.jpg",
      imgs: ["img/spots/odaiba-1.jpg", "img/spots/odaiba-3.jpg"],
      map: "Odaiba Seaside Park",
      lat: 35.6299,
      lng: 139.7752,
      day: 0,
      optional: true
    },
    {
      id: "rainbow",
      region: "tokyo",
      area: "台场",
      group: "备选 · 东京 · 台场",
      name: "彩虹大桥",
      en: "Rainbow Bridge",
      enter: "台场海滨或桥上步行道。外观免费。",
      duration: "40 分钟",
      note: "傍晚亮灯好看。和台场一起去，不要单独跑一趟。",
      guide: "彩虹大桥连接台场和港区，夜灯呈彩虹色，是东京湾的门户。桥本身是交通设施，被拍得多是因为它把海、车流和夜东京叠在一条线上。和台场海滨一起看就够，单独跑一趟不值得。",
      xhs: ["彩虹大桥夜景", "台场看彩虹大桥"],
      photo: "彩虹大桥",
      img: "img/spots/rainbow-1.jpg",
      imgs: ["img/spots/rainbow-1.jpg", "img/spots/rainbow-2.jpg", "img/spots/rainbow-3.jpg"],
      map: "Rainbow Bridge Tokyo",
      lat: 35.6366,
      lng: 139.7631,
      day: 0,
      optional: true
    },
    {
      id: "usj",
      region: "osaka",
      area: "大阪",
      group: "备选 · 大阪 · 下次再去",
      name: "大阪环球影城",
      en: "Universal Studios Japan",
      enter: "在大阪。新干线东京→新大阪约 2.5 小时，再换乘。这次六天主线不去。",
      duration: "一整天 + 来回交通",
      note: "哈利波特园区很好拍，但和东京、富士、迪士尼抢同一周。放进这 6 天就要砍掉河口湖或海洋。建议下次专门跑关西。",
      guide: "大阪环球影城是关西最强的主题乐园，哈利波特园区几乎是为拍照设计的。它不在东京，去了就要用掉一天再加新干线。这次六天主线是关东和富士，把它留到下次关西行，比硬塞进来更合理。",
      xhs: ["大阪环球影城", "USJ哈利波特"],
      photo: "环球影城",
      img: "img/spots/usj-1.jpg",
      imgs: ["img/spots/usj-1.jpg", "img/spots/usj-2.jpg", "img/spots/usj-3.jpg"],
      map: "Universal Studios Japan",
      lat: 34.6654,
      lng: 135.4323,
      day: 0,
      optional: true,
      onMap: false
    }
  ],
  days: [
    {
      id: 1,
      title: "浅草 · 秋叶原",
      date: "10/07 周三",
      stay: "新宿",
      from: "新宿酒店",
      where: "雷门、浅草寺、晴空塔、秋叶原夜景",
      path: "新宿 → 浅草雷门 / 仲见世 / 浅草寺 → 晴空塔 → 秋叶原夜景 → 回新宿",
      prep: [
        { item: "西瓜卡先充 3000–5000 日元", need: "必须提前", xhs: "iPhone西瓜卡" },
        { item: "晴空塔天望甲板指定时段票", need: "建议官网提前买", xhs: "东京晴空塔门票" },
        { item: "雷门、浅草寺、仲见世、秋叶原街道", need: "免费，不用预约" }
      ],
      beats: [
        { id: "d1a", time: "09:00", type: "commute", mode: "JR / 地铁", name: "新宿 → 浅草 · 约 30 分钟", lat: 35.7111, lng: 139.7964, cost: 200, detail: "打开 Google 地图搜「浅草」。常见：山手线到上野，换银座线到浅草。拍西瓜卡。" },
        { id: "d1b", time: "09:40", type: "spot", name: "雷门", spotId: "kaminarimon", cost: 0 },
        { id: "d1c", time: "10:00", type: "spot", name: "仲见世商店街", spotId: "nakamise", cost: 600 },
        { id: "d1d", time: "10:40", type: "spot", name: "浅草寺", spotId: "sensoji", cost: 0 },
        { id: "d1e", time: "12:00", type: "meal", name: "午饭 · 浅草天妇罗", lat: 35.7116, lng: 139.7952, xhs: "浅草天妇罗", cost: 1800, img: "img/spots/nakamise-1.jpg", photo: "浅草寺", detail: "寺附近天丼很多。不想排队就走侧巷。人均大约 1500–2000 日元。" },
        { id: "d1f", time: "13:40", type: "commute", mode: "步行 / 地铁", name: "浅草 → 晴空塔 · 约 20 分钟", lat: 35.7101, lng: 139.8107, cost: 180, detail: "沿隅田川走能拍到塔。腿累就坐地铁到押上。" },
        { id: "d1g", time: "14:10", type: "spot", name: "东京晴空塔", spotId: "skytree", cost: 2100 },
        { id: "d1h", time: "17:20", type: "commute", mode: "JR", name: "押上 → 秋叶原 · 约 15 分钟", lat: 35.6984, lng: 139.7731, cost: 180, detail: "半藏门线或 JR 到秋叶原。天黑前后到，灯更亮。" },
        { id: "d1i", time: "17:40", type: "spot", name: "秋叶原", spotId: "akihabara", cost: 0 },
        { id: "d1j", time: "19:20", type: "meal", name: "晚饭 · 秋叶原 / 回新宿", lat: 35.6986, lng: 139.7738, xhs: "秋叶原晚饭", cost: 1600, img: "img/spots/akihabara-1.jpg", photo: "秋叶原", detail: "拉面或定食即可。也可以坐山手线回新宿再吃。" },
        { id: "d1k", time: "20:40", type: "hotel", name: "新宿酒店", lat: 35.6909, lng: 139.6995, detail: "今晚住新宿标间。两人一间双床，护照都给前台。房费按一晚约 2 万日元估进当天花销。" }
      ]
    },
    {
      id: 2,
      title: "涩谷 · 东京塔",
      date: "10/08 周四",
      stay: "新宿",
      from: "新宿酒店",
      where: "明治神宫、竹下通、涩谷路口、东京塔夜景",
      path: "新宿 → 原宿明治神宫 → 竹下通 / 表参道 → 涩谷路口 → 东京塔亮灯",
      prep: [
        { item: "明治神宫、竹下通、表参道、涩谷路口", need: "免费，不用预约" },
        { item: "东京塔外观", need: "芝公园、增上寺免费拍；上塔再买票" },
        { item: "薄外套", need: "晚上拍塔会凉" }
      ],
      beats: [
        { id: "d2a", time: "09:20", type: "commute", mode: "JR", name: "新宿 → 原宿 · 约 6 分钟", lat: 35.6702, lng: 139.7027, cost: 160, detail: "山手线一站到原宿，出明治神宫口。" },
        { id: "d2b", time: "09:30", type: "spot", name: "明治神宫", spotId: "meiji", cost: 0 },
        { id: "d2c", time: "11:00", type: "spot", name: "竹下通", spotId: "takeshita", cost: 800 },
        { id: "d2d", time: "12:00", type: "meal", name: "午饭 · 原宿 / 表参道", lat: 35.6688, lng: 139.7068, xhs: "原宿午饭", cost: 1600, img: "img/spots/omotesando-1.jpg", photo: "表参道", detail: "可丽饼当垫饥的话，正餐去表参道点定食。人均大约 1500 日元。" },
        { id: "d2e", time: "13:20", type: "spot", name: "表参道", spotId: "omotesando", cost: 0 },
        { id: "d2f", time: "14:20", type: "commute", mode: "地铁", name: "表参道 → 涩谷 · 约 10 分钟", lat: 35.6595, lng: 139.7004, cost: 170, detail: "银座线一站到涩谷。" },
        { id: "d2g", time: "14:40", type: "spot", name: "涩谷十字路口 · 中心街", spotId: "shibuya", cost: 0 },
        { id: "d2h", time: "16:20", type: "commute", mode: "地铁", name: "涩谷 → 赤羽桥 / 神谷町 · 约 20 分钟", lat: 35.6586, lng: 139.7454, cost: 220, detail: "去东京塔。Google 地图搜 Tokyo Tower。尽量 16:40 前到增上寺机位等亮灯。" },
        { id: "d2i", time: "16:50", type: "spot", name: "东京塔", spotId: "tokyo-tower", cost: 0, detail: "先在增上寺山门框东京塔，再去芝公园拍全塔。上展望台另计，第一次拍外观通常就够。" },
        { id: "d2j", time: "19:00", type: "meal", name: "晚饭 · 芝 / 新宿", lat: 35.6580, lng: 139.7450, xhs: "东京塔附近晚饭", cost: 2200, img: "img/spots/tokyo-tower-2.jpg", photo: "东京塔", detail: "塔下或回新宿吃都可以。人均大约 2000 日元。" },
        { id: "d2k", time: "20:30", type: "hotel", name: "新宿酒店", lat: 35.6909, lng: 139.6995, detail: "还住新宿标间。明天迪士尼海洋要早起。" }
      ]
    },
    {
      id: 3,
      title: "迪士尼海洋",
      date: "10/09 周五",
      stay: "新宿",
      from: "新宿酒店",
      where: "东京迪士尼海洋（一整天）",
      path: "新宿 → 东京站 → 京叶线舞浜 → 海洋一整天 → 回新宿",
      prep: [
        { item: "东京迪士尼海洋指定日门票", need: "必须提前买，现场不售票；和乐园门票不能混用", xhs: "东京迪士尼海洋门票" },
        { item: "官方 App", need: "出发前下载" },
        { item: "园区午饭晚饭", need: "不用订" }
      ],
      beats: [
        { id: "d3a", time: "07:40", type: "commute", mode: "JR", name: "新宿 → 东京 → 舞浜 · 约 50 分钟", lat: 35.6267, lng: 139.8851, cost: 420, detail: "中央线快速到东京站，换京叶线到舞浜，再坐度假区线到海洋。开园前到先拍港湾。" },
        { id: "d3b", time: "08:50", type: "spot", name: "东京迪士尼海洋", spotId: "disneysea", cost: 9900 },
        { id: "d3c", time: "12:30", type: "meal", name: "午饭 · 园内", lat: 35.6269, lng: 139.8846, xhs: "迪士尼海洋午饭", cost: 1800, img: "img/spots/disneysea-2.jpg", photo: "东京迪士尼海洋", detail: "地中海港湾附近餐厅多。人均大约 1500–2000 日元。" },
        { id: "d3d", time: "18:00", type: "meal", name: "晚饭 · 园内", lat: 35.6264, lng: 139.8856, xhs: "迪士尼海洋晚餐", cost: 2200, img: "img/spots/disneysea-1.jpg", photo: "东京迪士尼海洋", detail: "尽量留到晚上看港湾灯和水上表演再走。" },
        { id: "d3e", time: "20:40", type: "commute", mode: "JR", name: "舞浜 → 新宿 · 约 55 分钟", lat: 35.6909, lng: 139.6995, cost: 420, detail: "原路返回。不要卡末班车。" },
        { id: "d3f", time: "21:40", type: "hotel", name: "新宿酒店", lat: 35.6909, lng: 139.6995, detail: "还住新宿标间。" }
      ]
    },
    {
      id: 4,
      title: "都心 · 东京站",
      date: "10/10 周六",
      stay: "新宿",
      from: "新宿酒店",
      where: "筑地、银座、皇居、东京站、新干线车头",
      path: "新宿 → 筑地早饭 → 银座 → 皇居二重桥 → 东京站 / 新干线 → 回新宿",
      prep: [
        { item: "筑地、银座、皇居外苑、东京站外观", need: "免费逛" },
        { item: "新干线站台", need: "进站台通常要票或站台票；只拍车站外观则不用" },
        { item: "银座周日才有步行者天国", need: "今天周六，正常有车" }
      ],
      beats: [
        { id: "d4a", time: "08:10", type: "commute", mode: "地铁", name: "新宿 → 筑地 · 约 30 分钟", lat: 35.6654, lng: 139.7707, cost: 220, detail: "去场外市场，不要去丰洲。" },
        { id: "d4b", time: "08:40", type: "spot", name: "筑地场外市场", spotId: "tsukiji", cost: 0 },
        { id: "d4c", time: "08:50", type: "meal", name: "早饭 · 筑地寿司 / 海鲜丼", lat: 35.6652, lng: 139.7704, xhs: "筑地早饭 寿司", cost: 2800, img: "img/spots/tsukiji-1.jpg", photo: "筑地市场", detail: "这顿当早午饭。人均 2500–4000 日元。先问能不能拍照。" },
        { id: "d4d", time: "10:40", type: "commute", mode: "步行", name: "筑地 → 银座 · 约 15 分钟", lat: 35.6712, lng: 139.7649, cost: 0, detail: "沿晴海通往西走。" },
        { id: "d4e", time: "11:00", type: "spot", name: "银座", spotId: "ginza", cost: 0 },
        { id: "d4f", time: "13:00", type: "commute", mode: "地铁", name: "银座 → 二重桥前 · 约 10 分钟", lat: 35.6802, lng: 139.7544, cost: 170, detail: "去皇居外苑。" },
        { id: "d4g", time: "13:20", type: "spot", name: "皇居外苑 · 二重桥", spotId: "imperial", cost: 0 },
        { id: "d4h", time: "14:20", type: "commute", mode: "步行", name: "二重桥 → 东京站 · 约 12 分钟", lat: 35.6812, lng: 139.7671, cost: 0, detail: "沿行幸通对着红砖车站走。" },
        { id: "d4i", time: "14:40", type: "spot", name: "东京站丸之内", spotId: "tokyo-station", cost: 0 },
        { id: "d4j", time: "15:30", type: "spot", name: "新干线（东京站拍车头）", spotId: "shinkansen", cost: 140, detail: "想拍车头：买站台票或用已有 JR 票进新干线口，拍完出站。这次不坐去大阪。" },
        { id: "d4k", time: "17:20", type: "commute", mode: "JR", name: "东京 → 新宿 · 约 15 分钟", lat: 35.6909, lng: 139.6995, cost: 200, detail: "中央线快速，方向高尾 / 立川。" },
        { id: "d4l", time: "19:00", type: "meal", name: "晚饭 · 新宿", lat: 35.6902, lng: 139.7028, xhs: "新宿晚饭", cost: 2500, img: "img/spots/ginza-1.jpg", photo: "新宿", detail: "歌舞伎町可以拍红门，吃饭选连锁店。不要跟拉客。" },
        { id: "d4m", time: "20:40", type: "hotel", name: "新宿酒店", lat: 35.6909, lng: 139.6995, detail: "还住新宿标间。明天河口湖要早起坐高速巴士。" }
      ]
    },
    {
      id: 5,
      title: "河口湖 · 富士山",
      date: "10/11 周日",
      stay: "新宿",
      from: "バスタ新宿",
      where: "河口湖、富士山观景",
      path: "新宿高速巴士 → 河口湖 → 湖畔 / 观景 → 巴士回新宿",
      prep: [
        { item: "新宿 → 河口湖高速巴士往返", need: "建议提前在 Highway Bus 或 Klook 买，周日容易满", xhs: "新宿河口湖巴士" },
        { item: "看富士山能见度预报", need: "出发前一晚看天气，云很多就改拍湖和红叶，别空跑" },
        { item: "薄羽绒或外套、舒适鞋", need: "湖边比东京凉" }
      ],
      beats: [
        { id: "d5a", time: "07:10", type: "commute", mode: "高速巴士", name: "バスタ新宿 → 河口湖 · 约 1 小时 45 分", lat: 35.4980, lng: 138.7686, cost: 2200, detail: "新宿站南口巴士总站。对号入座。行李放车厢下。单程大约 2000–2300 日元。" },
        { id: "d5b", time: "09:10", type: "spot", name: "富士山观景", spotId: "fuji", cost: 0, detail: "若去新仓山浅间公园，要从河口湖站再坐巴士或出租，并爬台阶。天气不好就不要硬爬。" },
        { id: "d5c", time: "11:30", type: "spot", name: "河口湖", spotId: "kawaguchiko", cost: 0 },
        { id: "d5d", time: "12:30", type: "meal", name: "午饭 · 河口湖", lat: 35.5175, lng: 138.7550, xhs: "河口湖午饭", cost: 1600, img: "img/spots/kawaguchiko-2.jpg", photo: "河口湖", detail: "湖边餐厅或便利店都可以。人均大约 1500 日元。" },
        { id: "d5e", time: "15:30", type: "commute", mode: "高速巴士", name: "河口湖 → 新宿 · 约 2 小时", lat: 35.6909, lng: 139.6995, cost: 2200, detail: "回程也提前订。周日晚高峰可能堵车，预留量。" },
        { id: "d5f", time: "18:00", type: "meal", name: "晚饭 · 新宿", lat: 35.6906, lng: 139.7005, xhs: "新宿拉面", cost: 1400, img: "img/spots/gyoen-2.jpg", photo: "新宿", detail: "回酒店附近随便吃。明天可能返程，不要喝太晚。" },
        { id: "d5g", time: "20:00", type: "hotel", name: "新宿酒店 · 收拾行李", lat: 35.6909, lng: 139.6995, detail: "今晚仍计一晚标间。明天 10/12 周一退房。护照、充电宝放随身包。" }
      ]
    },
    {
      id: 6,
      title: "新宿收尾 · 返程",
      date: "10/12 周一",
      stay: "回北京",
      from: "新宿酒店",
      where: "都厅或药妆，再去机场",
      path: "退房 → 都厅 / 买手信 → 利木津或 JR 去羽田 / 成田",
      prep: [
        { item: "新宿御苑周一休园", need: "今天不要去御苑；想去请提前换到其他天" },
        { item: "回程机票 + 机场交通", need: "羽田留 3 小时，成田留 4 小时" },
        { item: "液体、充电宝", need: "按登机规定装好" }
      ],
      beats: [
        { id: "d6a", time: "09:00", type: "hotel", name: "新宿酒店退房", lat: 35.6909, lng: 139.6995, checkout: true, detail: "今天退房，不再计房费。行李自己带；下午飞机可以先寄存在酒店或车站，中午前再取。" },
        { id: "d6b", time: "09:20", type: "spot", name: "都厅展望室", spotId: "tmg", cost: 0, detail: "白天也能看。时间紧就改去药妆。" },
        { id: "d6c", time: "10:30", type: "spot", name: "药妆 / 唐吉诃德", lat: 35.6912, lng: 139.7026, xhs: "新宿唐吉诃德 退税", cost: 0, img: "img/spots/shibuya-1.jpg", photo: "新宿", detail: "护照退税。不要买到来不及托运。" },
        { id: "d6d", time: "12:00", type: "meal", name: "午饭 · 新宿", lat: 35.6900, lng: 139.7020, xhs: "新宿午饭", cost: 1200, img: "img/spots/tmg-2.jpg", photo: "新宿", detail: "吃完就去机场。不要订太晚的饭。" },
        { id: "d6e", time: "13:00", type: "commute", mode: "利木津 / JR", name: "新宿 → 羽田或成田", lat: 35.5494, lng: 139.7798, cost: 1500, detail: "优先利木津巴士，行李放车下。的士贵，赶时间再打。" }
      ]
    }
  ]
};
